services:
  # Frontend application
  - type: web
    name: nextslide-frontend
    env: static
    repo: https://github.com/A-NextSlide/nextslide
    branch: main
    rootDirectory: apps/frontend
    buildCommand: rm -rf node_modules package-lock.json && npm install --production=false && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      # Fix MIME type for CSS files
      - path: /assets/*.css
        name: Content-Type
        value: text/css
      # Fix MIME type for JavaScript files
      - path: /assets/*.js
        name: Content-Type
        value: application/javascript
      # Fix MIME type for JavaScript modules
      - path: /assets/*.mjs
        name: Content-Type
        value: application/javascript
      # Cache static assets
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      # Handle client-side routing - serve index.html for all routes
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://nextslide-backend.onrender.com/api
      - key: VITE_AGENT_API_URL
        value: https://nextslide-backend.onrender.com
      - key: VITE_CHAT_API_URL
        value: https://nextslide-backend.onrender.com/api/chat
      - key: VITE_WEBSOCKET_URL
        value: wss://nextslide-websocket.onrender.com
      # Add your Supabase credentials as environment variables in Render dashboard
      # - key: VITE_SUPABASE_URL
      #   sync: false  # Set in dashboard
      # - key: VITE_SUPABASE_ANON_KEY
      #   sync: false  # Set in dashboard
      # - key: VITE_OPENAI_API_KEY
      #   sync: false  # Set in dashboard

  # WebSocket server
  - type: web
    name: nextslide-websocket
    env: docker
    repo: https://github.com/A-NextSlide/nextslide
    branch: main
    rootDirectory: apps/frontend
    dockerfilePath: ./Dockerfile.js
    plan: starter
    healthCheckPath: /
    buildCommand: ""  # Docker builds automatically from Dockerfile
    envVars:
      - key: NODE_ENV
        value: production

  # (Optional) Agent service removed from blueprint; frontend now points directly to Python backend