export interface ToolPageConfig {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  inputType: 'file-upload' | 'url-input' | 'text-area';
  acceptedFileTypes?: string;
  acceptedMimeTypes?: string[];
  heroSubtitle: string;
  processingMessage: string;
  howToSteps: string[];
  benefits: { icon: string; title: string; description: string }[];
  useCases: { title: string; description: string }[];
  faqs: { question: string; answer: string }[];
  heroGradient: string;
}

export const toolPages: ToolPageConfig[] = [
  {
    slug: 'pdf-to-ppt',
    title: 'PDF to PowerPoint Converter',
    metaTitle: 'Convert PDF to PowerPoint Free | NextSlide AI',
    metaDescription: 'Convert any PDF to an editable PowerPoint presentation in seconds. AI-powered PDF to PPT converter with smart layout detection. Free to use.',
    inputType: 'file-upload',
    acceptedFileTypes: '.pdf',
    acceptedMimeTypes: ['application/pdf'],
    heroSubtitle: 'Upload your PDF and let AI transform it into a polished, editable PowerPoint presentation with smart formatting.',
    processingMessage: 'Analyzing your PDF and generating slides...',
    howToSteps: [
      'Upload your PDF file (up to 50MB)',
      'Our AI analyzes the content, layout, and structure',
      'Review the extracted content and suggested slide layout',
      'Open in NextSlide to customize and export as PPTX',
    ],
    benefits: [
      { icon: 'Zap', title: 'Instant Conversion', description: 'Convert multi-page PDFs into slide decks in seconds, not hours of manual copy-pasting.' },
      { icon: 'Layout', title: 'Smart Layout Detection', description: 'AI identifies headings, bullet points, images, and tables to create properly structured slides.' },
      { icon: 'Paintbrush', title: 'Fully Editable Output', description: 'Every element is editable. Change text, move images, adjust colors, and add your branding.' },
      { icon: 'FileText', title: 'Preserves Content Quality', description: 'Text, charts, and images are extracted with high fidelity, so nothing gets lost in translation.' },
    ],
    useCases: [
      { title: 'Research Papers to Presentations', description: 'Turn academic papers, white papers, or industry reports into presentation-ready slide decks for conferences and meetings.' },
      { title: 'Sales Collateral Conversion', description: 'Convert PDF brochures, product sheets, and marketing materials into slides for your next sales pitch.' },
      { title: 'Training Manual Slides', description: 'Transform employee handbooks, SOPs, and training PDFs into engaging onboarding presentations.' },
      { title: 'Report Summaries', description: 'Distill lengthy PDF reports into concise executive summary presentations with key takeaways highlighted.' },
    ],
    faqs: [
      { question: 'What types of PDFs can I convert?', answer: 'You can convert virtually any PDF, including text-based documents, scanned pages, reports with charts, and PDFs with images. Our AI handles both simple text PDFs and complex multi-column layouts with graphics.' },
      { question: 'Is there a file size limit?', answer: 'The maximum file size is 50MB. For most PDFs, this covers documents up to several hundred pages. If your file is larger, consider splitting it into sections first.' },
      { question: 'Will the formatting be preserved?', answer: 'Our AI does its best to detect and preserve headings, bullet points, tables, and images. The output is a fully editable presentation, so you can fine-tune any formatting after conversion.' },
      { question: 'Can I edit the slides after conversion?', answer: 'Absolutely. Once converted, you can edit every element in NextSlide\u2019s editor \u2014 change text, rearrange slides, apply themes, add animations, and export to PPTX or Google Slides.' },
      { question: 'Is it free to convert PDF to PowerPoint?', answer: 'Yes. You can convert your first PDF completely free with no credit card required. For higher volume usage, check out our paid plans.' },
    ],
    heroGradient: 'from-red-600 via-rose-600 to-pink-600',
  },
  {
    slug: 'doc-to-ppt',
    title: 'Word Document to PowerPoint Converter',
    metaTitle: 'Convert Word to PowerPoint Free | NextSlide AI',
    metaDescription: 'Transform Word documents into professional presentations instantly. AI-powered DOC/DOCX to PPT converter. Free, no signup required.',
    inputType: 'file-upload',
    acceptedFileTypes: '.doc,.docx',
    acceptedMimeTypes: [
      'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    ],
    heroSubtitle: 'Upload your Word document and AI will transform it into a structured, professional presentation in seconds.',
    processingMessage: 'Reading your document and creating slides...',
    howToSteps: [
      'Upload your .doc or .docx file',
      'AI extracts headings, paragraphs, and key points',
      'Content is reorganized into clear, visual slides',
      'Open in NextSlide to refine and export',
    ],
    benefits: [
      { icon: 'FileText', title: 'Heading-Aware Parsing', description: 'AI uses your Word headings (H1, H2, H3) to create a logical slide structure automatically.' },
      { icon: 'Zap', title: 'Saves Hours of Work', description: 'Skip the tedious process of copying text from Word and formatting it in PowerPoint slide by slide.' },
      { icon: 'Sparkles', title: 'AI Content Refinement', description: 'Long paragraphs are condensed into concise bullet points optimized for presentations.' },
      { icon: 'Palette', title: 'Professional Themes', description: 'Choose from dozens of themes or let AI match colors to your brand after conversion.' },
    ],
    useCases: [
      { title: 'Proposal to Pitch Deck', description: 'Convert detailed written proposals into visual pitch decks that are easier for clients and stakeholders to digest.' },
      { title: 'Meeting Notes to Recap Slides', description: 'Turn meeting notes and minutes into shareable slide recaps for team members who missed the call.' },
      { title: 'Essay to Lecture Slides', description: 'Educators can transform written essays, lesson plans, or articles into classroom-ready slide presentations.' },
      { title: 'Brief to Strategy Deck', description: 'Convert marketing briefs, creative briefs, or strategy documents into polished presentation decks.' },
    ],
    faqs: [
      { question: 'Which Word formats are supported?', answer: 'We support both .doc (legacy Word format) and .docx (modern Word format). Both are processed the same way. We recommend .docx for best results.' },
      { question: 'Does it preserve images from my Word doc?', answer: 'Yes. Embedded images, charts, and tables in your Word document are extracted and placed into the corresponding slides.' },
      { question: 'How does AI decide what goes on each slide?', answer: 'The AI uses your document structure (headings, subheadings, paragraphs) to determine slide breaks. Each major section typically becomes one or more slides.' },
      { question: 'Can I convert long documents?', answer: 'Yes. Documents up to 50MB are supported. For very long documents, the AI will create a comprehensive deck and you can remove slides you do not need.' },
      { question: 'Is my document data secure?', answer: 'Your files are processed securely and are not stored permanently. We use encrypted connections and delete uploaded files after processing.' },
    ],
    heroGradient: 'from-blue-600 via-indigo-600 to-violet-600',
  },
  {
    slug: 'notes-to-presentation',
    title: 'Notes to Presentation Converter',
    metaTitle: 'Turn Notes into Slides Instantly | NextSlide AI',
    metaDescription: 'Paste your notes and get a professional presentation in seconds. AI organizes your ideas into clear, visual slides. Free to start.',
    inputType: 'text-area',
    heroSubtitle: 'Paste your notes, bullet points, or rough ideas and watch AI turn them into a polished slide deck.',
    processingMessage: 'Organizing your notes into slides...',
    howToSteps: [
      'Paste or type your notes into the text box',
      'AI identifies key topics and organizes them into sections',
      'Each section becomes a well-designed slide',
      'Open in NextSlide to customize and present',
    ],
    benefits: [
      { icon: 'Brain', title: 'AI-Powered Organization', description: 'Messy notes become structured presentations. AI finds the narrative thread in your ideas.' },
      { icon: 'Clock', title: 'Minutes, Not Hours', description: 'Go from raw notes to a finished deck in under 60 seconds instead of spending an afternoon formatting.' },
      { icon: 'Sparkles', title: 'Professional Quality', description: 'AI applies design principles so your slides look polished even if you have zero design experience.' },
      { icon: 'Pencil', title: 'Easy Refinement', description: 'The AI gives you a strong starting point. Tweak wording, reorder slides, and add visuals in the editor.' },
    ],
    useCases: [
      { title: 'Meeting Notes to Slides', description: 'Convert your meeting notes into a shareable presentation for stakeholders who were not in the room.' },
      { title: 'Brainstorm to Deck', description: 'Turn brainstorming session bullet points into a structured proposal or strategy presentation.' },
      { title: 'Lecture Notes to Teaching Slides', description: 'Transform handwritten or typed lecture notes into classroom slides with proper formatting.' },
      { title: 'Quick Idea Pitches', description: 'Got a rough idea for a product or initiative? Paste your notes and get a quick pitch deck to share.' },
    ],
    faqs: [
      { question: 'How much text should I paste?', answer: 'Anything from a few bullet points to several pages of notes works. We recommend at least a few sentences so the AI has enough context to create meaningful slides.' },
      { question: 'Do my notes need to be organized?', answer: 'Not at all. The AI is designed to take unstructured, messy notes and find a logical structure. Just paste whatever you have.' },
      { question: 'Can I paste text from other apps?', answer: 'Yes. Copy and paste from Google Docs, Apple Notes, Notion, Evernote, or any other text source. Formatting will be interpreted by the AI.' },
      { question: 'How many slides will it create?', answer: 'The number of slides depends on how much content you provide. A few bullet points might produce 5-8 slides, while longer notes can generate 15 or more.' },
      { question: 'Can I control the slide count?', answer: 'Yes. After initial generation, you can add or remove slides in the editor. You can also specify a desired slide count before generating.' },
    ],
    heroGradient: 'from-emerald-600 via-teal-600 to-cyan-600',
  },
  {
    slug: 'pitch-deck-generator',
    title: 'AI Pitch Deck Generator',
    metaTitle: 'AI Pitch Deck Generator Free | NextSlide',
    metaDescription: 'Generate a professional pitch deck in 60 seconds. Describe your startup and AI creates investor-ready slides. Free, no design skills needed.',
    inputType: 'text-area',
    heroSubtitle: 'Describe your startup, product, or idea and get an investor-ready pitch deck generated by AI in seconds.',
    processingMessage: 'Generating your pitch deck...',
    howToSteps: [
      'Describe your startup or business idea',
      'AI generates a complete pitch deck structure',
      'Review slides covering problem, solution, market, and traction',
      'Customize in the editor and share with investors',
    ],
    benefits: [
      { icon: 'Rocket', title: 'Investor-Ready Format', description: 'AI uses proven pitch deck frameworks (problem, solution, market, traction, team, ask) trusted by top VCs.' },
      { icon: 'Clock', title: '60-Second Generation', description: 'Stop spending weeks on your pitch deck. Get a professional first draft in under a minute.' },
      { icon: 'TrendingUp', title: 'Data-Driven Slides', description: 'AI includes charts and metrics placeholders so you can add your traction data easily.' },
      { icon: 'Palette', title: 'Polished Design', description: 'Clean, modern slide designs that look like they were made by a professional designer.' },
    ],
    useCases: [
      { title: 'Seed Round Fundraising', description: 'Create a compelling pitch deck to secure your first round of funding from angel investors or seed funds.' },
      { title: 'Accelerator Applications', description: 'Build a polished deck for YC, Techstars, or other accelerator demo days and application processes.' },
      { title: 'Internal Stakeholder Buy-In', description: 'Present a new product idea or initiative to leadership with a structured, professional proposal deck.' },
      { title: 'Startup Competitions', description: 'Generate a competition-ready pitch deck for hackathons, business plan competitions, and pitch events.' },
    ],
    faqs: [
      { question: 'What should I write in the text box?', answer: 'Describe your startup in a few sentences: what problem you solve, who your customers are, what makes you different, and where you are now (revenue, users, etc.). The more detail you provide, the better the deck.' },
      { question: 'Does it follow a standard pitch deck structure?', answer: 'Yes. The AI follows the widely accepted pitch deck format: Title, Problem, Solution, Market Size, Business Model, Traction, Team, Competition, Financials, and Ask.' },
      { question: 'Can I customize the deck after generation?', answer: 'Absolutely. Every slide is fully editable. You can change text, rearrange slides, add your own data, swap images, and apply your brand colors.' },
      { question: 'Is it really free?', answer: 'Yes. You can generate your first pitch deck completely free. No credit card required. Paid plans unlock additional features like custom branding and higher usage limits.' },
      { question: 'How does this compare to hiring a designer?', answer: 'A freelance deck designer costs $500-$5,000 and takes days to weeks. NextSlide generates a strong starting point in seconds. Many founders use it as a first draft, then refine it themselves.' },
    ],
    heroGradient: 'from-violet-600 via-purple-600 to-fuchsia-600',
  },
  {
    slug: 'website-to-ppt',
    title: 'Website to PowerPoint Converter',
    metaTitle: 'Convert Website to PowerPoint | NextSlide AI',
    metaDescription: 'Turn any website or URL into a professional PowerPoint presentation. AI extracts content and creates slides automatically. Free to try.',
    inputType: 'url-input',
    heroSubtitle: 'Paste any website URL and AI will extract the content and transform it into a professional slide deck.',
    processingMessage: 'Fetching website content and creating slides...',
    howToSteps: [
      'Paste the URL of any website or webpage',
      'AI scrapes and analyzes the page content',
      'Key information is organized into presentation slides',
      'Open in NextSlide to edit, brand, and export',
    ],
    benefits: [
      { icon: 'Globe', title: 'Any Website Works', description: 'Paste a blog post, landing page, documentation, or any public URL and get slides instantly.' },
      { icon: 'Zap', title: 'Automatic Extraction', description: 'AI pulls text, headings, images, and key data from the page without you lifting a finger.' },
      { icon: 'Layout', title: 'Smart Slide Structure', description: 'Content is organized into logical slides with proper hierarchy, not just dumped onto one page.' },
      { icon: 'FileText', title: 'Multiple Page Support', description: 'Works with articles, product pages, documentation, blog posts, and more.' },
    ],
    useCases: [
      { title: 'Blog Post to Presentation', description: 'Repurpose your best blog content into slide decks for webinars, social media, and internal presentations.' },
      { title: 'Competitor Analysis', description: 'Convert competitor websites and product pages into slides for competitive analysis presentations.' },
      { title: 'Product Page to Sales Deck', description: 'Turn your product or landing page into a sales presentation you can share with prospects.' },
      { title: 'Research and Reference', description: 'Convert research articles and documentation pages into reference slides for your team.' },
    ],
    faqs: [
      { question: 'What types of URLs work?', answer: 'Any publicly accessible URL works, including blog posts, news articles, product pages, landing pages, documentation, and Wikipedia articles. Private or login-protected pages cannot be accessed.' },
      { question: 'Does it capture images from the website?', answer: 'Yes. The AI extracts key images from the page and includes them in the presentation where relevant. You can add, remove, or replace images in the editor.' },
      { question: 'How long does conversion take?', answer: 'Most websites are converted in 15-30 seconds. Longer pages with lots of content may take up to a minute.' },
      { question: 'Can I convert multiple pages at once?', answer: 'Currently, you convert one URL at a time. For multi-page content, you can create separate decks and combine slides in the editor.' },
      { question: 'Does it work with dynamic JavaScript-rendered pages?', answer: 'Our crawler handles most modern websites including those with JavaScript rendering. Some highly dynamic single-page apps may not be fully captured.' },
    ],
    heroGradient: 'from-sky-600 via-blue-600 to-indigo-600',
  },
  {
    slug: 'google-slides-to-ppt',
    title: 'Google Slides to PowerPoint Converter',
    metaTitle: 'Google Slides to PowerPoint Free | NextSlide AI',
    metaDescription: 'Convert Google Slides to PowerPoint with AI enhancement. Upload your exported .pptx and get an improved, editable presentation. Free.',
    inputType: 'file-upload',
    acceptedFileTypes: '.pptx',
    acceptedMimeTypes: [
      'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    ],
    heroSubtitle: 'Export your Google Slides as .pptx, upload here, and let AI enhance your presentation with better design and formatting.',
    processingMessage: 'Analyzing your presentation and enhancing slides...',
    howToSteps: [
      'Export your Google Slides deck as .pptx (File > Download > PowerPoint)',
      'Upload the .pptx file here',
      'AI analyzes each slide and suggests design improvements',
      'Open in NextSlide to review enhancements and export',
    ],
    benefits: [
      { icon: 'Sparkles', title: 'AI Design Enhancement', description: 'AI improves slide layouts, typography, and visual hierarchy beyond what Google Slides offers.' },
      { icon: 'Paintbrush', title: 'Better Formatting', description: 'Fix alignment issues, inconsistent fonts, and poor spacing that often occur in Google Slides exports.' },
      { icon: 'ArrowRightLeft', title: 'Seamless Conversion', description: 'Your content transfers perfectly. No lost text, broken images, or missing animations.' },
      { icon: 'Download', title: 'Export Anywhere', description: 'After enhancement, export to PPTX, PDF, or share via link. Works with PowerPoint, Keynote, and more.' },
    ],
    useCases: [
      { title: 'Upgrade Slide Design', description: 'Take a basic Google Slides deck and give it a professional makeover with AI-powered design suggestions.' },
      { title: 'Cross-Platform Compatibility', description: 'Ensure your Google Slides deck looks perfect in PowerPoint for clients who use Microsoft Office.' },
      { title: 'Team Deck Standardization', description: 'Standardize slide formatting across your team by running everyone\'s decks through the AI enhancer.' },
      { title: 'Presentation Polish', description: 'Give a final design polish to important presentations before big meetings or conferences.' },
    ],
    faqs: [
      { question: 'Why do I need to export as .pptx first?', answer: 'Google Slides does not allow direct access to files from external tools. Exporting as .pptx (File > Download > Microsoft PowerPoint) gives us the file we need to analyze and enhance your slides.' },
      { question: 'Will my slide animations be preserved?', answer: 'Basic animations and transitions are preserved in the .pptx export. Complex Google Slides-specific animations may be simplified during the conversion.' },
      { question: 'Can I go back to Google Slides after?', answer: 'Yes. You can download the enhanced presentation as .pptx and upload it back to Google Slides at any time.' },
      { question: 'What improvements does AI make?', answer: 'AI can improve text layout, font consistency, color harmony, image placement, slide structure, and overall visual hierarchy. It focuses on making your content more impactful.' },
      { question: 'Does it change my content?', answer: 'No. The AI only improves design and layout. Your text, images, and data remain exactly as you wrote them.' },
    ],
    heroGradient: 'from-yellow-500 via-orange-500 to-red-500',
  },
  {
    slug: 'improve-my-slides',
    title: 'AI Slide Improver',
    metaTitle: 'Improve Your Slides with AI | NextSlide',
    metaDescription: 'Upload your existing PowerPoint and let AI redesign it. Better layouts, cleaner text, and professional polish. Free to try.',
    inputType: 'file-upload',
    acceptedFileTypes: '.ppt,.pptx',
    acceptedMimeTypes: [
      'application/vnd.ms-powerpoint',
      'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    ],
    heroSubtitle: 'Upload your existing PowerPoint deck and AI will analyze each slide, suggest improvements, and redesign it.',
    processingMessage: 'Analyzing your slides and finding improvements...',
    howToSteps: [
      'Upload your .ppt or .pptx file',
      'AI reviews every slide for design and content quality',
      'Get AI-powered suggestions for layout, text, and visuals',
      'Apply improvements and export your polished deck',
    ],
    benefits: [
      { icon: 'Sparkles', title: 'AI Design Review', description: 'Get an instant design critique with specific, actionable suggestions for every slide.' },
      { icon: 'Layout', title: 'Layout Optimization', description: 'AI fixes cluttered slides, improves white space usage, and creates better visual flow.' },
      { icon: 'Type', title: 'Text Refinement', description: 'Wordy slides get condensed into punchy, presentation-ready bullet points.' },
      { icon: 'Palette', title: 'Color and Theme Fixes', description: 'AI harmonizes colors, fixes contrast issues, and ensures brand consistency across all slides.' },
    ],
    useCases: [
      { title: 'Pre-Meeting Polish', description: 'Upload your deck the night before a big presentation and get AI-powered improvements in minutes.' },
      { title: 'Template Refresh', description: 'Breathe new life into outdated company templates with modern design improvements.' },
      { title: 'Student Presentation Help', description: 'Students can upload their class presentations and get professional design feedback instantly.' },
      { title: 'Consultant Deck Enhancement', description: 'Consultants can quickly polish client deliverables with AI-powered design improvements.' },
    ],
    faqs: [
      { question: 'What file formats are supported?', answer: 'We support both .ppt (legacy PowerPoint) and .pptx (modern PowerPoint) formats. For best results, use .pptx.' },
      { question: 'Will it change my content?', answer: 'The AI focuses on design improvements. It may suggest condensing long text blocks, but it will not change the meaning of your content.' },
      { question: 'How many slides can I improve at once?', answer: 'There is no slide limit. Upload a deck of any length and AI will analyze every slide. Files up to 50MB are supported.' },
      { question: 'Can I accept or reject individual suggestions?', answer: 'Yes. In the editor, you can review each AI suggestion and decide whether to apply it. You have full control over the final output.' },
      { question: 'Does it work with custom fonts?', answer: 'AI works with any fonts embedded in your PowerPoint file. If custom fonts are not embedded, system fonts will be substituted.' },
    ],
    heroGradient: 'from-amber-500 via-orange-500 to-red-500',
  },
  {
    slug: 'text-to-ppt',
    title: 'Text to PowerPoint Converter',
    metaTitle: 'Convert Text to PowerPoint Free | NextSlide AI',
    metaDescription: 'Turn any text into a professional PowerPoint presentation. Just paste your content and AI creates beautiful slides. Free and instant.',
    inputType: 'text-area',
    heroSubtitle: 'Paste any text \u2014 an article, essay, email, or report \u2014 and AI will create a professional presentation from it.',
    processingMessage: 'Converting your text into slides...',
    howToSteps: [
      'Paste or type your text content',
      'AI identifies key themes and structures the content',
      'Text is transformed into visual, well-designed slides',
      'Open in NextSlide to fine-tune and export as PPTX',
    ],
    benefits: [
      { icon: 'Zap', title: 'Instant Transformation', description: 'Paste any amount of text and get presentation-ready slides in seconds.' },
      { icon: 'Brain', title: 'Intelligent Summarization', description: 'AI distills long-form text into concise slide content while preserving key messages.' },
      { icon: 'Layout', title: 'Smart Slide Breaks', description: 'AI determines optimal slide breaks based on topic changes and content density.' },
      { icon: 'Download', title: 'Export Ready', description: 'Download as PowerPoint, PDF, or share directly via link. Compatible with all major tools.' },
    ],
    useCases: [
      { title: 'Article to Webinar Deck', description: 'Convert published articles or blog posts into presentation format for webinars and speaking engagements.' },
      { title: 'Email Summary to Slides', description: 'Turn lengthy email threads or updates into concise slide summaries for team meetings.' },
      { title: 'Book Chapter to Lecture', description: 'Transform textbook chapters or reading materials into lecture slides for classroom use.' },
      { title: 'Report to Executive Slides', description: 'Condense written reports into executive-friendly slide presentations with key findings highlighted.' },
    ],
    faqs: [
      { question: 'How much text can I paste?', answer: 'You can paste up to approximately 50,000 characters (roughly 25 pages of text). For longer documents, consider uploading as a file instead.' },
      { question: 'Does the AI just copy text onto slides?', answer: 'No. The AI actively restructures, summarizes, and designs each slide. Long paragraphs become concise bullets, key points are highlighted, and visual hierarchy is applied.' },
      { question: 'What language does it support?', answer: 'The AI works with any language that uses Latin, Cyrillic, or CJK scripts. English produces the best results, but other major languages are well supported.' },
      { question: 'Can I paste formatted text?', answer: 'Yes. If you paste from a rich-text source, the AI will interpret the formatting. Plain text works perfectly as well.' },
      { question: 'How is this different from Notes to Presentation?', answer: 'Text to PPT is optimized for longer-form, structured text like articles and reports. Notes to Presentation is better for rough, unstructured bullet points and ideas.' },
    ],
    heroGradient: 'from-teal-600 via-cyan-600 to-blue-600',
  },
  {
    slug: 'csv-to-ppt',
    title: 'CSV to PowerPoint Converter',
    metaTitle: 'Convert CSV to PowerPoint Charts | NextSlide AI',
    metaDescription: 'Turn CSV and Excel data into presentation-ready charts and slides. AI creates beautiful data visualizations. Free to start.',
    inputType: 'file-upload',
    acceptedFileTypes: '.csv,.xlsx,.xls',
    acceptedMimeTypes: [
      'text/csv',
      'application/vnd.ms-excel',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    ],
    heroSubtitle: 'Upload your CSV or Excel file and AI will create beautiful charts, tables, and data-driven slides.',
    processingMessage: 'Analyzing your data and creating charts...',
    howToSteps: [
      'Upload your .csv, .xlsx, or .xls file',
      'AI analyzes columns, rows, and data patterns',
      'Data is visualized as charts, tables, and key-metric slides',
      'Open in NextSlide to customize visualizations and export',
    ],
    benefits: [
      { icon: 'BarChart3', title: 'Auto Chart Generation', description: 'AI picks the right chart type for your data \u2014 bar, line, pie, or scatter \u2014 so you do not have to.' },
      { icon: 'Table', title: 'Smart Table Formatting', description: 'Raw spreadsheet data is formatted into clean, readable tables with proper headers and styling.' },
      { icon: 'TrendingUp', title: 'Insight Extraction', description: 'AI identifies trends, outliers, and key metrics in your data and highlights them on dedicated slides.' },
      { icon: 'Sparkles', title: 'Presentation-Ready Design', description: 'Charts and tables are styled to look professional and match your presentation theme.' },
    ],
    useCases: [
      { title: 'Sales Reports', description: 'Upload monthly sales data and get a complete slide deck with revenue charts, growth metrics, and trend analysis.' },
      { title: 'Survey Results Presentation', description: 'Convert survey response data into visual charts and summary slides for stakeholder presentations.' },
      { title: 'Financial Summaries', description: 'Turn financial spreadsheets into investor-friendly slides with clear charts and KPI dashboards.' },
      { title: 'Research Data Visualization', description: 'Present research data with professionally designed charts and statistical summaries.' },
    ],
    faqs: [
      { question: 'What data formats are supported?', answer: 'We support CSV (.csv), Excel (.xlsx), and legacy Excel (.xls) files. For CSV files, use comma or semicolon delimiters.' },
      { question: 'How does AI choose chart types?', answer: 'The AI analyzes your data structure: time series data gets line charts, categorical comparisons get bar charts, proportions get pie charts, and correlations get scatter plots.' },
      { question: 'Can I change the charts after generation?', answer: 'Yes. All charts are fully editable in the NextSlide editor. You can change chart types, colors, labels, and data ranges.' },
      { question: 'Is there a row or column limit?', answer: 'Files up to 50MB are supported, which covers most spreadsheets. For extremely large datasets, consider filtering to the most relevant data first.' },
      { question: 'Will it show all my data or just summaries?', answer: 'The AI creates a mix of detailed data tables and summary charts. It focuses on the most impactful views of your data while keeping the full picture available.' },
    ],
    heroGradient: 'from-green-600 via-emerald-600 to-teal-600',
  },
  {
    slug: 'image-to-ppt',
    title: 'Image to PowerPoint Converter',
    metaTitle: 'Convert Images to PowerPoint | NextSlide AI',
    metaDescription: 'Turn images into professional presentations. Upload photos, screenshots, or graphics and AI creates slides with context. Free.',
    inputType: 'file-upload',
    acceptedFileTypes: '.png,.jpg,.jpeg,.gif,.webp',
    acceptedMimeTypes: [
      'image/png',
      'image/jpeg',
      'image/gif',
      'image/webp',
    ],
    heroSubtitle: 'Upload images, screenshots, or graphics and AI will build a professional presentation around your visual content.',
    processingMessage: 'Analyzing your images and creating slides...',
    howToSteps: [
      'Upload one or more images (PNG, JPG, GIF, WebP)',
      'AI analyzes the visual content and extracts context',
      'Each image becomes a slide with AI-generated titles and descriptions',
      'Open in NextSlide to arrange, edit, and export',
    ],
    benefits: [
      { icon: 'Image', title: 'Visual Content Analysis', description: 'AI understands what is in your images and generates relevant titles, captions, and context for each slide.' },
      { icon: 'Layout', title: 'Professional Layouts', description: 'Images are placed in professional slide layouts with proper sizing, alignment, and white space.' },
      { icon: 'FileText', title: 'Auto-Generated Text', description: 'AI writes slide titles, bullet points, and descriptions based on the visual content of your images.' },
      { icon: 'Layers', title: 'Multi-Image Support', description: 'Upload multiple images and get a complete deck with each image on its own professionally designed slide.' },
    ],
    useCases: [
      { title: 'Photo Portfolio Presentation', description: 'Turn a collection of photos into a polished portfolio presentation for clients or interviews.' },
      { title: 'Screenshot Walkthrough', description: 'Create product walkthroughs or tutorials from UI screenshots with AI-generated explanatory text.' },
      { title: 'Design Review Deck', description: 'Compile design mockups and wireframes into a presentation for stakeholder review meetings.' },
      { title: 'Event Recap', description: 'Upload event photos and create a recap presentation with AI-generated captions and highlights.' },
    ],
    faqs: [
      { question: 'What image formats are supported?', answer: 'We support PNG, JPG/JPEG, GIF, and WebP formats. For best results, use high-resolution images (at least 800px wide).' },
      { question: 'Can I upload multiple images?', answer: 'Yes. Upload as many images as you need. Each image will be placed on its own slide with AI-generated content.' },
      { question: 'Does AI understand what is in my images?', answer: 'Yes. Our AI uses vision models to analyze image content, identify objects, read text in images, and generate relevant descriptions and slide titles.' },
      { question: 'What is the maximum image size?', answer: 'Individual images can be up to 50MB. For optimal performance, we recommend images under 10MB each.' },
      { question: 'Can I add text to the image slides?', answer: 'Absolutely. AI auto-generates titles and descriptions, but you can edit, add, or remove any text in the NextSlide editor.' },
    ],
    heroGradient: 'from-pink-600 via-rose-600 to-red-600',
  },
];

export const toolRedirects: { from: string; to: string }[] = [
  { from: '/pdf-to-presentation', to: '/pdf-to-ppt' },
  { from: '/doc-to-presentation', to: '/doc-to-ppt' },
  { from: '/notes-to-ppt', to: '/notes-to-presentation' },
  { from: '/website-to-presentation', to: '/website-to-ppt' },
  { from: '/link-to-ppt', to: '/website-to-ppt' },
  { from: '/link-to-presentation', to: '/website-to-ppt' },
  { from: '/csv-to-presentation', to: '/csv-to-ppt' },
  { from: '/data-to-ppt', to: '/csv-to-ppt' },
  { from: '/data-to-presentation', to: '/csv-to-ppt' },
];

export function getToolPageBySlug(slug: string): ToolPageConfig | undefined {
  return toolPages.find((t) => t.slug === slug);
}
