import React, { useState, useRef, useEffect, useCallback } from 'react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { cn } from '@/lib/utils';
import { Send, Sparkles, ArrowLeft, FileText, Upload, X, Link as LinkIcon, Image as ImageIcon, Table, Presentation, File, Paperclip, Loader2 } from 'lucide-react';
import { VoiceRecorder } from '@/components/voice/VoiceRecorder';
import { streamOutlineAgentChat, ChatMessage, AgentEvent, OutlineData, FileAttachment, generateSlideContent } from '@/services/outlineAgentService';
import { fileToBase64, getFileCategory, formatFileSize, createImagePreview, revokeImagePreview } from '@/services/fileAnalysisService';
import { ThinkingStatusDisplay, ThemeChatBlock, DropdownOutlineChatBlock } from '@/components/chat';
import type { ThemeBlockData, OutlineBlockData, OutlineSlide, DropdownOutlineBlockData } from '@/components/chat';
import { ThinkingStep, StatusPhase, STATUS_PHASES } from '@/types/agentEvents';
import { ThemeEditorData, OutlinePreviewData, ThemeColorPalette } from '@/types/chatBlocks';
import { useFontLoader } from '@/hooks/useFontLoading';
import { useThemeStore } from '@/stores/themeStore';
import { billingApi } from '@/services/billingApi';
import { CreditWarningDialog, CreditWarningMode } from '@/components/billing/CreditWarningDialog';

// Helper to render markdown-like formatting
const renderText = (text: string) => {
  const parts: React.ReactNode[] = [];
  let lastIndex = 0;

  // Match **bold** text
  const boldRegex = /\*\*([^*]+)\*\*/g;
  let match;

  while ((match = boldRegex.exec(text)) !== null) {
    // Add text before bold
    if (match.index > lastIndex) {
      parts.push(text.slice(lastIndex, match.index));
    }
    // Add bold text with theme font
    parts.push(
      <strong key={match.index} className="font-semibold">
        {match[1]}
      </strong>
    );
    lastIndex = match.index + match[0].length;
  }

  // Add remaining text
  if (lastIndex < text.length) {
    parts.push(text.slice(lastIndex));
  }

  return parts.length > 0 ? parts : text;
};

interface AttachmentPreview {
  id: string;
  name: string;
  type: string;
  size: number;
  previewUrl?: string;
}

interface Message {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
  buttons?: Array<{
    label: string;
    action: string;
  }>;
  showPresentationSelection?: boolean;
  showSlideModeSelection?: boolean;
  attachments?: AttachmentPreview[];
  // Inline chat blocks
  themeBlock?: ThemeEditorData;
  outlineBlock?: OutlinePreviewData;
}

interface CollectedData {
  topic?: string;
  stylePreferences?: string;
  // Style/vibe for theme generation (e.g., "modern", "playful", "corporate", brand name, or domain)
  style?: string;
  slideCount?: number;
  detailLevel?: 'quick' | 'standard' | 'detailed';
  presentationType?: 'simple' | 'detailed';
  slideMode?: 'interactive' | 'static';  // 'interactive' = NextGen, 'static' = Traditional PPT
  chatHistory?: { role: 'user' | 'assistant'; content: string }[];
  themeChanges?: any;
  uploadedFiles?: File[];
  uploadedMedia?: Array<{
    id: string;
    name: string;
    type: string;
    content?: string;
    url?: string;
    size?: number;
  }>;
  // Slide screenshots from uploaded PPT/PDF for visual design reference
  slideScreenshots?: string[];  // Base64 encoded PNG screenshots
  // CRITICAL: Slides generated by the outline agent - pass these to avoid regeneration!
  slides?: Array<{
    title: string;
    subtitle?: string;
    content?: string;
    key_points?: string[];
  }>;
  // Narrative explanation from the agent about the presentation
  narrative?: string;
}

type ConversationStage =
  | 'conversing'
  | 'planning'
  | 'slide_mode_selection'
  | 'confirmed'
  | 'chat';

interface ConversationalOnboardingProps {
  onComplete: (data: CollectedData) => void;
  onCancel?: () => void;
  initialMessage?: string;
  slideCount?: number;
  onProcessingChange?: (isProcessing: boolean) => void;
  initialUploadedFiles?: File[];
}

const ConversationalOnboarding: React.FC<ConversationalOnboardingProps> = ({
  onComplete,
  onCancel,
  initialMessage,
  slideCount,
  onProcessingChange,
  initialUploadedFiles = []
}) => {
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState('');
  const [isAgentTyping, setIsAgentTyping] = useState(false);
  const [chatHistory, setChatHistory] = useState<ChatMessage[]>([]);
  const [isProcessing, setIsProcessing] = useState(false);
  const [collectedData, setCollectedData] = useState<CollectedData>({ slideCount });
  const [stage, setStage] = useState<ConversationStage>('conversing');
  const [outlineFlow, setOutlineFlow] = useState<any>(null);
  const [uploadedFiles, setUploadedFiles] = useState<Array<{ file: File; previewUrl?: string }>>(
    initialUploadedFiles.map(f => ({
      file: f,
      previewUrl: f.type.startsWith('image/') ? createImagePreview(f) : undefined
    }))
  );
  // Persistent files that have been sent but need to be resent with each message until outline is generated
  const [persistentFiles, setPersistentFiles] = useState<FileAttachment[]>([]);
  // Track which files have already been analyzed to avoid re-analyzing on every message
  const [analyzedFileNames, setAnalyzedFileNames] = useState<Set<string>>(new Set());
  // Store the file analysis context to include in chat history instead of re-sending files
  const [fileAnalysisContext, setFileAnalysisContext] = useState<string | null>(null);
  const [isDraggingOver, setIsDraggingOver] = useState(false);
  const [isUploadingFiles, setIsUploadingFiles] = useState(false);
  const [statusMessage, setStatusMessage] = useState<string | null>(null);
  const [statusPhase, setStatusPhase] = useState<string | null>(null);
  // File upload confirmation - ask if for reference or direct use
  const [pendingFileConfirmation, setPendingFileConfirmation] = useState<{
    files: Array<{ file: File; previewUrl?: string }>;
  } | null>(null);

  // Thinking steps for rich progress display
  const [thinkingSteps, setThinkingSteps] = useState<ThinkingStep[]>([]);
  // Streaming text from model (for showing thoughts line-by-line)
  const [streamingText, setStreamingText] = useState<string>('');

  // Inline theme editor state
  const [themeBlock, setThemeBlock] = useState<ThemeEditorData | null>(null);
  const [themeBlockCollapsed, setThemeBlockCollapsed] = useState(true); // Start collapsed
  const [isThemeLoading, setIsThemeLoading] = useState(false); // Track theme generation
  const [outlineBlock, setOutlineBlock] = useState<OutlinePreviewData | null>(null);
  const [outlineBlockCollapsed, setOutlineBlockCollapsed] = useState(true); // Start collapsed

  // Credit warning dialog state
  const [showCreditWarning, setShowCreditWarning] = useState(false);
  const [creditWarningData, setCreditWarningData] = useState<{
    remaining: number;
    required: number;
    slideCount: number;
    planName: string;
    mode: CreditWarningMode;
    pendingSlideMode?: 'interactive' | 'static';
  } | null>(null);

  // Font loader and theme store
  const { loadThemeFonts, isLoading: isFontLoading } = useFontLoader();
  const { setOutlineDeckTheme, getOutlineDeckTheme } = useThemeStore();

  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Helper to add thinking step
  const addThinkingStep = useCallback((status: string, message?: string, query?: string) => {
    const phaseConfig = STATUS_PHASES[status as StatusPhase] || {
      icon: '⋯',
      label: status,
      color: '#6B7280',
      activeLabel: status,
    };

    const step: ThinkingStep = {
      id: `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      phase: status,
      label: phaseConfig.activeLabel || phaseConfig.label,
      detail: message || query,
      status: 'active',
      timestamp: new Date(),
    };

    setThinkingSteps(prev => {
      // Mark previous step as completed
      const updated = prev.map(s => ({ ...s, status: 'completed' as const }));
      return [...updated, step];
    });
  }, []);

  // Clear thinking steps
  const clearThinkingSteps = useCallback(() => {
    setThinkingSteps([]);
  }, []);

  // Build theme block from outline data - always creates a theme with defaults
  const buildThemeBlockFromOutline = useCallback((outlineData: OutlineData): ThemeEditorData => {
    const stylePrefs = outlineData.stylePreferences || {};
    const colors = stylePrefs.colors || {};

    // Default playful colors for Pikachu-like topics, professional otherwise
    const topic = (outlineData.topic || '').toLowerCase();
    const isPlayful = ['pikachu', 'pokemon', 'game', 'cartoon', 'fun', 'kids'].some(k => topic.includes(k));

    const defaultColors = isPlayful
      ? { bg: '#FFDC00', text: '#1A1A1A', accent1: '#FF4301', accent2: '#3B4CCA' }  // Yellow/Red/Blue
      : { bg: '#FFFFFF', text: '#1F2937', accent1: '#FF4301', accent2: '#3B82F6' }; // White/Orange/Blue

    return {
      themeId: `theme-${Date.now()}`,
      colors: {
        primary_background: colors.background || defaultColors.bg,
        primary_text: colors.text || defaultColors.text,
        accent_1: colors.accent1 || defaultColors.accent1,
        accent_2: colors.accent2 || colors.accent1 || defaultColors.accent2,
        colors: [colors.accent1, colors.accent2, colors.accent3].filter(Boolean) as string[] || [defaultColors.accent1, defaultColors.accent2],
        backgrounds: [colors.background].filter(Boolean) as string[] || [defaultColors.bg],
      },
      typography: {
        headingFont: stylePrefs.font || (isPlayful ? 'Fredoka' : 'Inter'),
        bodyFont: stylePrefs.bodyFont || (isPlayful ? 'Nunito' : 'Inter'),
      },
      branding: {
        logoUrl: stylePrefs.logoUrl,
        brandName: outlineData.brandContext,
        brandDomain: outlineData.brandContext,
      },
      designStyle: outlineData.style || (isPlayful ? 'playful' : 'modern'),
      vibeContext: outlineData.brandContext || outlineData.style || outlineData.topic,
      isEditable: true,
    };
  }, []);

  // Handle theme color change from inline editor
  const handleThemeColorChange = useCallback((colorKey: keyof ThemeColorPalette | string, hex: string) => {
    setThemeBlock(prev => {
      if (!prev) return prev;
      return {
        ...prev,
        colors: {
          ...prev.colors,
          [colorKey]: hex,
        },
      };
    });
  }, []);

  // Handle theme font change from inline editor
  const handleThemeFontChange = useCallback(async (fontType: 'heading' | 'body', fontFamily: string) => {
    // Load the font first
    await loadThemeFonts(
      fontType === 'heading' ? fontFamily : themeBlock?.typography.headingFont || 'Inter',
      fontType === 'body' ? fontFamily : themeBlock?.typography.bodyFont || 'Inter'
    );

    setThemeBlock(prev => {
      if (!prev) return prev;
      return {
        ...prev,
        typography: {
          ...prev.typography,
          [fontType === 'heading' ? 'headingFont' : 'bodyFont']: fontFamily,
        },
      };
    });
  }, [loadThemeFonts, themeBlock]);

  // Handle brand change from inline editor
  const handleBrandChange = useCallback((brand: { name?: string; logoUrl?: string }) => {
    setThemeBlock(prev => {
      if (!prev) return prev;
      return {
        ...prev,
        branding: {
          ...prev.branding,
          brandName: brand.name ?? prev.branding?.brandName,
          logoUrl: brand.logoUrl ?? prev.branding?.logoUrl,
        },
      };
    });
  }, []);

  // Apply theme to store (and by extension, the deck)
  const applyThemeToStore = useCallback(() => {
    if (!themeBlock) return;

    // Build theme payload in the format expected by the theme store
    const colors = themeBlock.colors;
    const accentsArray = [colors.accent_1, colors.accent_2].filter(Boolean);

    const themePayload = {
      color_palette: {
        primary_background: colors.primary_background,
        primary_text: colors.primary_text,
        accent_1: colors.accent_1,
        accent_2: colors.accent_2,
        // CRITICAL: accent_1, accent_2 at FRONT tells AI which are primary brand colors
        colors: [...accentsArray, ...(colors.colors || [])],
        backgrounds: colors.backgrounds || [colors.primary_background],
        text_colors: { primary: colors.primary_text },
        metadata: {
          logo_url: themeBlock.branding?.logoUrl,
        },
      },
      typography: {
        hero_title: { family: themeBlock.typography.headingFont },
        body_text: { family: themeBlock.typography.bodyFont },
      },
    };

    // Store in theme store
    setOutlineDeckTheme(themePayload);

    // Also update collected data stylePreferences
    setCollectedData(prev => ({
      ...prev,
      stylePreferences: JSON.stringify({
        colors: {
          type: 'custom',
          background: colors.primary_background,
          text: colors.primary_text,
          accent1: colors.accent_1,
          accent2: colors.accent_2,
        },
        font: themeBlock.typography.headingFont,
        bodyFont: themeBlock.typography.bodyFont,
        logoUrl: themeBlock.branding?.logoUrl,
        vibeContext: themeBlock.vibeContext,
      }),
    }));

    console.log('[ConversationalOnboarding] Applied theme to store:', themePayload);
  }, [themeBlock, setOutlineDeckTheme]);

  // Notify parent of processing state changes
  useEffect(() => {
    onProcessingChange?.(isProcessing || isAgentTyping);
  }, [isProcessing, isAgentTyping, onProcessingChange]);

  // Scroll to bottom when messages change, thinking steps update, or streaming text changes
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, thinkingSteps, isAgentTyping, streamingText]);

  // Auto-focus input
  useEffect(() => {
    inputRef.current?.focus();
  }, []);

  // Initial welcome message or process initial message
  useEffect(() => {
    console.log('[ConversationalOnboarding] 🎬 Component mounted');
    console.log('[ConversationalOnboarding] - initialMessage:', initialMessage);
    console.log('[ConversationalOnboarding] - slideCount:', slideCount);
    console.log('[ConversationalOnboarding] - initialUploadedFiles:', initialUploadedFiles?.length || 0);

    if (initialMessage) {
      handleSendMessage(initialMessage);
    } else {
      setTimeout(() => {
        addAgentMessage(
          "What would you like to create a presentation about?"
        );
      }, 500);
    }
  }, []);

  const addMessage = (
    role: 'user' | 'assistant',
    content: string,
    buttons?: Array<{ label: string; action: string }>,
    showPresentationSelection?: boolean,
    attachments?: AttachmentPreview[],
    showSlideModeSelection?: boolean
  ) => {
    const newMessage: Message = {
      id: `${Date.now()}-${Math.random()}`,
      role,
      content,
      timestamp: new Date(),
      buttons,
      showPresentationSelection,
      showSlideModeSelection,
      attachments
    };
    setMessages(prev => [...prev, newMessage]);

    // Update chat history for agent (don't include selection prompts)
    if (!showPresentationSelection && !showSlideModeSelection) {
      setChatHistory(prev => [...prev, { role, content }]);
    }
  };

  const addAgentMessage = (content: string, buttons?: Array<{ label: string; action: string }>) => {
    setIsAgentTyping(true);
    setTimeout(() => {
      addMessage('assistant', content, buttons);
      setIsAgentTyping(false);
    }, 800);
  };

  const handleSendMessage = async (messageText?: string) => {
    const userMessage = messageText || input.trim();
    if ((!userMessage && uploadedFiles.length === 0) || isProcessing) return;

    // Snapshot current files for this message
    const currentFiles = [...uploadedFiles];
    const hasFiles = currentFiles.length > 0;

    // Create attachment previews for the message before clearing
    const messageAttachments: AttachmentPreview[] = currentFiles.map((f, idx) => ({
      id: `file-${Date.now()}-${idx}`,
      name: f.file.name,
      type: f.file.type || 'application/octet-stream',
      size: f.file.size,
      previewUrl: f.previewUrl
    }));

    setInput('');
    setIsProcessing(true);
    onProcessingChange?.(true);

    // Add user message WITH attachments shown in the message
    addMessage('user', userMessage || (hasFiles ? `Shared ${currentFiles.length} file${currentFiles.length > 1 ? 's' : ''}` : ''), undefined, undefined, messageAttachments.length > 0 ? messageAttachments : undefined);

    // Clear uploaded files UI after adding to message (but keep references for API call)
    setUploadedFiles([]);

    try {
      setIsAgentTyping(true);
      // Clear streaming text at the start of each message
      setStreamingText('');

      // Convert new files to base64 and add to persistent files
      let newFilesToAdd: FileAttachment[] = [];
      if (hasFiles) {
        console.log('[ConversationalOnboarding] Converting', currentFiles.length, 'new files to base64...');
        newFilesToAdd = await Promise.all(
          currentFiles.map(async (f, idx) => {
            const content = await fileToBase64(f.file);
            console.log('[ConversationalOnboarding] Converted:', f.file.name, 'base64 length:', content.length);
            return {
              id: `file-${Date.now()}-${idx}`,
              name: f.file.name,
              type: f.file.type || 'application/octet-stream',
              content,
              size: f.file.size
            };
          })
        );
        // Add to persistent files so they're sent with every message
        setPersistentFiles(prev => [...prev, ...newFilesToAdd]);
      }

      // Only send files that haven't been analyzed yet to avoid re-analyzing on every message
      const allPersistentFiles = [...persistentFiles, ...newFilesToAdd];
      const filesToSend = allPersistentFiles.filter(f => !analyzedFileNames.has(f.name));
      console.log('[ConversationalOnboarding] Sending', filesToSend.length, 'NEW files (total persistent:', allPersistentFiles.length, ', already analyzed:', analyzedFileNames.size, ')');

      // Stream agent response
      let assistantMessage = '';
      let outlineData: OutlineData | null = null;

      // Include file analysis context in the request if files were previously analyzed
      const contextWithFileAnalysis = {
        ...collectedData,
        // Include previous file analysis so agent knows about files even without re-analyzing
        ...(fileAnalysisContext && filesToSend.length === 0 ? { previousFileAnalysis: fileAnalysisContext } : {})
      };

      // Debug logging to track what's being sent
      console.log('[ConversationalOnboarding] 🚀 Calling streamOutlineAgentChat:');
      console.log('[ConversationalOnboarding] - userMessage:', userMessage);
      console.log('[ConversationalOnboarding] - chatHistory length:', chatHistory.length);
      console.log('[ConversationalOnboarding] - chatHistory:', JSON.stringify(chatHistory.slice(-3))); // Last 3 messages
      console.log('[ConversationalOnboarding] - context:', JSON.stringify(contextWithFileAnalysis));
      console.log('[ConversationalOnboarding] - files:', filesToSend.length);

      const generator = streamOutlineAgentChat({
        message: userMessage || 'Please analyze these files for my presentation.',
        chat_history: chatHistory,
        context: contextWithFileAnalysis,
        files: filesToSend.length > 0 ? filesToSend : undefined
      });

      for await (const event of generator) {
        if (event.type === 'text') {
          assistantMessage += event.content;
          // Update streaming text for live display (show thoughts as they come in)
          setStreamingText(prev => prev + event.content);
          // Clear status when we get actual text
          setStatusMessage(null);
          setStatusPhase(null);
        } else if (event.type === 'status') {
          // Handle status updates - show to user with rich thinking steps
          console.log('[ConversationalOnboarding] Status:', event.status, event.message);
          const status = (event as any).status;
          const message = (event as any).message || (event as any).query;

          // Add thinking step for rich progress display
          addThinkingStep(status, message, (event as any).query);

          // Map status to user-friendly messages (for fallback display)
          if (status === 'thinking') {
            setStatusPhase('thinking');
            setStatusMessage('Processing your request...');
          } else if (status === 'analyzing_file') {
            setStatusPhase('analyzing');
            setStatusMessage(`Analyzing ${(event as any).file_name || 'file'}...`);
          } else if (status === 'files_analyzed') {
            setStatusPhase('analyzed');
            setStatusMessage(`Analyzed ${(event as any).analyses?.length || 1} file(s)`);
            // Track which files have been analyzed so we don't re-send them
            const analyses = (event as any).analyses || [];
            const analyzedNames = analyses.map((a: any) => a.name || a.filename).filter(Boolean);
            if (analyzedNames.length > 0) {
              setAnalyzedFileNames(prev => new Set([...prev, ...analyzedNames]));
              console.log('[ConversationalOnboarding] Tracked analyzed files:', analyzedNames);
              // Store a summary of file analysis for context in subsequent messages
              const summaries = analyses.map((a: any) => `${a.name || a.filename}: ${a.summary || 'analyzed'}`).join('\n');
              setFileAnalysisContext(summaries);
            }
          } else if (status === 'file_analysis_error') {
            setStatusPhase('error');
            setStatusMessage(message || 'Could not analyze file');
          } else if (status === 'researching') {
            setStatusPhase('researching');
            setStatusMessage(`Searching: ${(event as any).query || 'web'}...`);
          } else if (status === 'scraping') {
            setStatusPhase('scraping');
            setStatusMessage(message || 'Reading content...');
          } else if (status === 'scraped') {
            setStatusPhase('scraped');
            setStatusMessage(message || 'Content extracted');
          } else {
            setStatusMessage(message || status);
          }
        } else if (event.type === 'outline') {
          // IMPORTANT: Don't overwrite generate_outline with subsequent update_theme
          // The agent may output both in the same response, and we need to keep the generate_outline
          if (!outlineData || outlineData.action !== 'generate_outline') {
            outlineData = event.data;
          } else if (event.data?.action === 'update_theme' && outlineData.action === 'generate_outline') {
            // Store theme changes in the existing generate_outline data
            outlineData.theme_changes = event.data.theme_changes;
            console.log('[ConversationalOnboarding] Merged theme update into generate_outline');
          }
          console.log('[ConversationalOnboarding] Received outline data:', outlineData);
          setStatusMessage(null);
          setStatusPhase(null);
        } else if (event.type === 'error') {
          console.error('[ConversationalOnboarding] Agent error:', event.message);
          setStatusMessage(null);
          setStatusPhase(null);
          addAgentMessage("I apologize, but I encountered an error. Let's try again. What would you like your presentation to be about?");
          setIsAgentTyping(false);
          setIsProcessing(false);
          return;
        }
      }

      setIsAgentTyping(false);
      setStatusMessage(null);
      setStatusPhase(null);
      clearThinkingSteps();

      // Check if agent wants to generate outline
      if (outlineData && outlineData.action === 'generate_outline') {
        // Agent has created the flow! Show it and ask for presentation type
        setStage('planning');
        setOutlineFlow(outlineData);
        // Clear persistent files now that outline is generated - they're included in outlineData.uploadedMedia
        // BUT keep fileAnalysisContext - we need it for generating slide content on demand
        console.log('[ConversationalOnboarding] Outline generated, clearing', persistentFiles.length, 'persistent files and', analyzedFileNames.size, 'analyzed file names');
        console.log('[ConversationalOnboarding] Keeping fileAnalysisContext for slide content generation:', fileAnalysisContext?.slice(0, 100));
        setPersistentFiles([]);
        setAnalyzedFileNames(new Set());
        // Don't clear fileAnalysisContext - we need it for the dropdown outline content generation!

        // Build theme block - fetch brand colors if we have brandContext
        console.log('[ConversationalOnboarding] 🎨 Building theme from outlineData:', {
          topic: outlineData.topic,
          stylePreferences: outlineData.stylePreferences,
          brandContext: outlineData.brandContext,
          style: outlineData.style,
        });

        // Start with defaults, then fetch real theme from backend
        let newThemeBlock = buildThemeBlockFromOutline(outlineData);
        setThemeBlock(newThemeBlock);
        setThemeBlockCollapsed(true);

        // ALWAYS attempt to fetch theme colors from backend
        // Use brandContext, style, or topic as vibeContext for theme generation
        const vibeContext = outlineData.brandContext || outlineData.style || outlineData.topic;
        if (vibeContext) {
          // Set loading state BEFORE calling API
          setIsThemeLoading(true);

          const themeMessage = outlineData.brandContext
            ? `Fetching brand colors for ${outlineData.brandContext}...`
            : 'Generating theme colors...';
          console.log('[ConversationalOnboarding] 🏷️ Theme generation:', vibeContext);
          addThinkingStep('fetching_brand', themeMessage, vibeContext);

          // Call theme generation API to get brand colors
          (async () => {
            try {
              const { outlineApi } = await import('@/services/outlineApi');
              const tempOutlineId = `temp-${Date.now()}`;

              const themeOutline = {
                id: tempOutlineId,
                title: outlineData.topic || 'Presentation',
                slides: outlineData.slides?.map((s, i) => ({
                  id: `slide-${i}`,
                  title: s.title,
                  content: s.content || s.key_points?.join('\n') || '',
                })) || [{ id: 'slide-0', title: outlineData.topic || 'Presentation', content: '' }],
                stylePreferences: {
                  initialIdea: outlineData.topic,
                  vibeContext: vibeContext,
                }
              };

              console.log('[ConversationalOnboarding] 🎨 Calling generateThemeFromOutline with vibeContext:', vibeContext);

              const themeResult = await outlineApi.generateThemeFromOutline(
                themeOutline as any,
                tempOutlineId,
                (evt) => {
                  console.log('[ConversationalOnboarding] 🎨 Theme event:', evt.type, evt);
                  if ((evt as any).type === 'theme_generated' || (evt as any).type === 'theme_preview_update') {
                    const theme = (evt as any).theme || evt;
                    if (theme?.color_palette) {
                      console.log('[ConversationalOnboarding] ✅ Got brand colors:', theme.color_palette);
                      console.log('[ConversationalOnboarding] 🖼️ Theme logo fields:', {
                        brandInfo_logoUrl: theme.brandInfo?.logoUrl,
                        color_palette_metadata_logo_url: theme.color_palette?.metadata?.logo_url,
                        logo: theme.logo,
                        logo_info: theme.logo_info,
                        style_preferences_logoUrl: theme.style_preferences?.logoUrl,
                        stylePreferences_logoUrl: theme.stylePreferences?.logoUrl,
                        direct_logoUrl: (theme as any).logoUrl,
                      });
                      // Update theme block with brand colors
                      setThemeBlock(prev => {
                        if (!prev) return prev;
                        return {
                          ...prev,
                          colors: {
                            primary_background: theme.color_palette.primary_background || prev.colors.primary_background,
                            primary_text: theme.color_palette.primary_text || prev.colors.primary_text,
                            accent_1: theme.color_palette.accent_1 || prev.colors.accent_1,
                            accent_2: theme.color_palette.accent_2 || prev.colors.accent_2,
                            colors: theme.color_palette.colors || prev.colors.colors,
                            backgrounds: theme.color_palette.backgrounds || prev.colors.backgrounds,
                          },
                          typography: {
                            headingFont: theme.typography?.hero_title?.family || prev.typography.headingFont,
                            bodyFont: theme.typography?.body_text?.family || prev.typography.bodyFont,
                          },
                          branding: {
                            ...prev.branding,
                            // Logo can be in many places depending on source
                            logoUrl: theme.brandInfo?.logoUrl ||
                                     theme.color_palette?.metadata?.logo_url ||
                                     theme.logo?.url ||
                                     theme.logo_info?.url ||
                                     theme.style_preferences?.logoUrl ||
                                     theme.stylePreferences?.logoUrl ||
                                     (theme as any).logoUrl ||
                                     prev.branding?.logoUrl,
                          },
                        };
                      });
                      // Theme received - stop loading
                      setIsThemeLoading(false);
                      completeThinkingStep('fetching_brand');
                    }
                  }
                }
              );

              // Also check the final result
              if (themeResult?.theme?.color_palette) {
                console.log('[ConversationalOnboarding] ✅ Final theme result:', themeResult.theme);
                setIsThemeLoading(false);
              }
            } catch (err) {
              console.error('[ConversationalOnboarding] ❌ Failed to fetch brand colors:', err);
              setIsThemeLoading(false);
              completeThinkingStep('fetching_brand');
            }
          })();
        } else {
          // No vibeContext, no theme loading needed
          setIsThemeLoading(false);
        }

        // Load fonts
        loadThemeFonts(newThemeBlock.typography.headingFont, newThemeBlock.typography.bodyFont);
        console.log('[ConversationalOnboarding] ✅ Built initial theme block:', newThemeBlock);

        // Build outline block for preview - include ALL content that will be on slides
        if (outlineData.slides && outlineData.slides.length > 0) {
          console.log('[ConversationalOnboarding] 📋 Building outline block with', outlineData.slides.length, 'slides');
          const outlinePreview: OutlinePreviewData = {
            outlineId: `outline-${Date.now()}`,
            title: outlineData.topic || 'Your Presentation',
            slides: outlineData.slides.map((s, i) => ({
              id: `slide-${i}`,
              title: s.title,
              subtitle: s.subtitle,
              keyPoints: s.key_points,
              content: s.content, // Include narrative/content if available
            })),
          };
          setOutlineBlock(outlinePreview);
          setOutlineBlockCollapsed(true); // Keep collapsed for compact view
          console.log('[ConversationalOnboarding] ✅ Built outline block:', outlinePreview);
        } else {
          console.log('[ConversationalOnboarding] ⚠️ No slides in outlineData');
        }

        // Show the planning message with inline blocks
        addAgentMessage(
          assistantMessage || "Here's the plan for your presentation:"
        );

        // Check if user requested detailed mode in their messages
        const userRequestedDetailed = chatHistory.some(msg =>
          msg.role === 'user' &&
          (msg.content.toLowerCase().includes('detailed') ||
           msg.content.toLowerCase().includes('in-depth') ||
           msg.content.toLowerCase().includes('comprehensive'))
        );

        // Store detail level for later use
        const detailLevel = userRequestedDetailed ? 'detailed' : 'quick';
        setCollectedData(prev => ({ ...prev, presentationType: 'simple', detailLevel }));

        // Ask about slide mode (interactive vs static)
        setTimeout(() => {
          console.log('[ConversationalOnboarding] 🔄 Setting stage to slide_mode_selection, blocks:', {
            hasThemeBlock: !!themeBlock,
            hasOutlineBlock: !!outlineBlock,
          });
          setStage('slide_mode_selection');
          addMessage(
            'assistant',
            "Your presentation is ready to generate!",
            undefined,
            undefined,
            undefined,
            true // showSlideModeSelection
          );
        }, 1500);
      } else if (outlineData && outlineData.action === 'update_theme') {
        // Agent wants to update the theme
        console.log('[ConversationalOnboarding] Received theme update:', outlineData.theme_changes);

        setCollectedData(prev => ({
          ...prev,
          themeChanges: outlineData.theme_changes
        }));

        // Clean the message to remove buttons and JSON
        const cleanedMessage = assistantMessage
          .replace(/\[Button:[^\]]+\]/g, '')
          .replace(/```json[\s\S]*?```/g, '')
          .trim();

        // Acknowledge the theme update
        addAgentMessage(cleanedMessage || "I've noted your branding preferences.");
      } else {
        // Continue conversation
        // Parse for suggested buttons in the message (format: [Button: Label | action])
        const buttonMatches = assistantMessage.matchAll(/\[Button:\s*([^\|]+)\s*\|\s*([^\]]+)\]/g);
        const buttons: Array<{ label: string; action: string }> = [];

        for (const match of buttonMatches) {
          buttons.push({
            label: match[1].trim(),
            action: match[2].trim()
          });
        }

        // Remove button markup and JSON blocks from message
        const cleanedMessage = assistantMessage
          .replace(/\[Button:[^\]]+\]/g, '')
          .replace(/```json[\s\S]*?```/g, '')
          .trim();

        // Update collected data if agent mentions specific details
        const newCollectedData = { ...collectedData };

        // Extract topic if mentioned
        if (assistantMessage.toLowerCase().includes('topic') || assistantMessage.toLowerCase().includes('about')) {
          newCollectedData.topic = userMessage;
        }

        // Extract style preferences if mentioned
        if (assistantMessage.toLowerCase().includes('style') || assistantMessage.toLowerCase().includes('vibe')) {
          newCollectedData.stylePreferences = userMessage;
        }

        setCollectedData(newCollectedData);
        addMessage('assistant', cleanedMessage, buttons.length > 0 ? buttons : undefined);
      }
    } catch (error) {
      console.error('[ConversationalOnboarding] Error:', error);
      addAgentMessage("I'm sorry, I encountered an issue. Could you please try rephrasing that?");
    } finally {
      setIsProcessing(false);
      setStatusMessage(null);
      setStatusPhase(null);
      setStreamingText(''); // Clear streaming text when done
      // Auto-focus input after processing is done and input is re-enabled
      setTimeout(() => {
        inputRef.current?.focus();
      }, 100);
    }
  };

  // Proceed with generation after credit check passes
  const proceedWithGeneration = (slideMode: 'interactive' | 'static') => {
    const modeLabel = slideMode === 'interactive'
      ? 'NextGen'
      : 'Traditional';

    addMessage('user', modeLabel);
    setCollectedData(prev => ({ ...prev, slideMode }));
    setStage('confirmed');

    // Apply theme to store BEFORE completing (so it's available for generation)
    applyThemeToStore();

    const confirmMessage = slideMode === 'interactive'
      ? "Creating your next-generation interactive presentation..."
      : "Creating your beautifully designed traditional presentation...";

    addAgentMessage(confirmMessage);

    setTimeout(() => {
      console.log('[ConversationalOnboarding] Passing outline data to onComplete:');
      console.log('[ConversationalOnboarding] - outlineFlow?.slides:', outlineFlow?.slides?.length, 'slides');
      console.log('[ConversationalOnboarding] - outlineFlow?.topic:', outlineFlow?.topic);
      console.log('[ConversationalOnboarding] - style sources: brandContext=', outlineFlow?.brandContext, 'vibeContext=', outlineFlow?.stylePreferences?.vibeContext, 'style=', outlineFlow?.style);

      // Build stylePreferences from theme block if available
      const stylePreferencesFromTheme = themeBlock ? {
        colors: {
          type: 'custom' as const,
          background: themeBlock.colors.primary_background,
          text: themeBlock.colors.primary_text,
          accent1: themeBlock.colors.accent_1,
          accent2: themeBlock.colors.accent_2,
        },
        font: themeBlock.typography.headingFont,
        bodyFont: themeBlock.typography.bodyFont,
        logoUrl: themeBlock.branding?.logoUrl,
        vibeContext: themeBlock.vibeContext,
      } : null;

      onComplete({
        ...collectedData,
        topic: outlineFlow?.topic || collectedData.topic,
        // Style for theme generation (e.g., brand name, domain, or style descriptor)
        // Agent outputs this as brandContext, or it can be in stylePreferences.vibeContext
        style: outlineFlow?.brandContext || outlineFlow?.stylePreferences?.vibeContext || outlineFlow?.style || collectedData.style,
        // Pass the edited stylePreferences from theme block if available
        stylePreferences: stylePreferencesFromTheme ? JSON.stringify(stylePreferencesFromTheme) : collectedData.stylePreferences,
        slideCount: collectedData.slideCount || outlineFlow?.slide_count,
        detailLevel: collectedData.detailLevel || 'quick',
        presentationType: 'simple',
        slideMode,
        chatHistory: chatHistory,
        themeChanges: collectedData.themeChanges || outlineFlow?.theme_changes,
        uploadedFiles: uploadedFiles.map(f => f.file),
        uploadedMedia: outlineFlow?.uploadedMedia,
        // Pass slide screenshots for visual design replication
        slideScreenshots: outlineFlow?.slide_screenshots,
        // CRITICAL: Pass the slides generated by the agent to avoid re-generation!
        slides: outlineFlow?.slides,
      });
    }, 1500);
  };

  const handleButtonClick = async (action: string) => {
    // Handle slide mode selection - 2 modes: NextGen (interactive) and Traditional (static)
    if (action === 'interactive' || action === 'static') {
      const slideMode = action as 'interactive' | 'static';

      // Set processing state immediately for UI feedback
      setIsProcessing(true);

      // Check credits BEFORE proceeding with generation
      const numSlides = outlineFlow?.slides?.length || outlineBlock?.slides?.length || collectedData.slideCount || 5;
      const creditsPerSlide = 5;
      const requiredCredits = numSlides * creditsPerSlide;

      try {
        const balance = await billingApi.getBalance();
        const remainingCredits = balance.remaining_credits;
        const planName = balance.plan_name || 'free';
        const isPaidPlan = ['starter', 'pro', 'enterprise'].includes(planName.toLowerCase());

        console.log('[ConversationalOnboarding] Credit check:', {
          remainingCredits,
          requiredCredits,
          numSlides,
          planName,
          isPaidPlan,
          canUseOverage: balance.can_use_overage,
        });

        // Determine if we need to show a warning
        if (remainingCredits < requiredCredits) {
          let mode: CreditWarningMode;

          if (remainingCredits === 0) {
            mode = isPaidPlan ? 'paid_overage' : 'free_no_credits';
          } else {
            mode = isPaidPlan ? 'paid_overage' : 'free_low_credits';
          }

          // Persist outline data to localStorage so user can resume after upgrading
          const outlineDataToSave = {
            outlineFlow,
            outlineBlock,
            themeBlock,
            collectedData,
            chatHistory,
            pendingSlideMode: slideMode,
            savedAt: new Date().toISOString(),
          };
          localStorage.setItem('nextslide_pending_outline', JSON.stringify(outlineDataToSave));
          console.log('[ConversationalOnboarding] Saved outline to localStorage for post-upgrade resume');

          // Show credit warning dialog
          setCreditWarningData({
            remaining: remainingCredits,
            required: requiredCredits,
            slideCount: numSlides,
            planName,
            mode,
            pendingSlideMode: slideMode,
          });
          setShowCreditWarning(true);
          setIsProcessing(false); // Reset processing state when showing dialog
          return; // Don't proceed until user confirms
        }

        // Credits are sufficient, proceed with generation
        proceedWithGeneration(slideMode);

      } catch (error) {
        console.error('[ConversationalOnboarding] Failed to check credits:', error);
        // If we can't check credits, proceed anyway (backend will handle it)
        // Don't reset isProcessing since proceedWithGeneration will transition to generation
        proceedWithGeneration(slideMode);
      }

      return;
    }

    handleSendMessage(action);
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey && !e.ctrlKey && !e.metaKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  // Auto-resize textarea
  useEffect(() => {
    if (inputRef.current) {
      inputRef.current.style.height = 'auto';
      inputRef.current.style.height = `${Math.min(inputRef.current.scrollHeight, 400)}px`;
    }
  }, [input]);

  // File upload handlers
  const MAX_FILE_SIZE = 30 * 1024 * 1024; // 30MB limit (Anthropic supports up to 32MB)

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files || []);
    const validFiles: Array<{ file: File; previewUrl?: string }> = [];
    const oversizedFiles: string[] = [];

    files.forEach(file => {
      if (file.size > MAX_FILE_SIZE) {
        oversizedFiles.push(file.name);
      } else {
        validFiles.push({
          file,
          previewUrl: file.type.startsWith('image/') ? createImagePreview(file) : undefined
        });
      }
    });

    if (oversizedFiles.length > 0) {
      // Show a message about oversized files
      addMessage('assistant', `⚠️ ${oversizedFiles.join(', ')} ${oversizedFiles.length > 1 ? 'are' : 'is'} too large (max 30MB). Please use smaller files or compress them.`);
    }

    if (validFiles.length > 0) {
      // Show confirmation dialog asking how to use the files
      setPendingFileConfirmation({ files: validFiles });
    }
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  // Handle file confirmation - user chooses how to use uploaded files
  const handleFileConfirmation = (useDirectly: boolean) => {
    if (!pendingFileConfirmation) return;

    const { files } = pendingFileConfirmation;
    setUploadedFiles(prev => [...prev, ...files]);

    if (useDirectly) {
      // Add instruction for AI to use content directly
      const fileNames = files.map(f => f.file.name).join(', ');
      addMessage('user', `Use the content from ${fileNames} directly in the slides. Don't summarize or change it - use it exactly as provided.`);
    } else {
      // Files are for reference/inspiration only
      const fileNames = files.map(f => f.file.name).join(', ');
      addMessage('user', `I've uploaded ${fileNames} for reference and design inspiration. Use it to inform the style and structure but create fresh content.`);
    }

    setPendingFileConfirmation(null);
  };

  const handleRemoveFile = (index: number) => {
    setUploadedFiles(prev => {
      const toRemove = prev[index];
      if (toRemove?.previewUrl) {
        revokeImagePreview(toRemove.previewUrl);
      }
      return prev.filter((_, i) => i !== index);
    });
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDraggingOver(true);
  };

  const handleDragLeave = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDraggingOver(false);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDraggingOver(false);

    const files = Array.from(e.dataTransfer.files);
    const validFiles: Array<{ file: File; previewUrl?: string }> = [];
    const oversizedFiles: string[] = [];

    files.forEach(file => {
      if (file.size > MAX_FILE_SIZE) {
        oversizedFiles.push(file.name);
      } else {
        validFiles.push({
          file,
          previewUrl: file.type.startsWith('image/') ? createImagePreview(file) : undefined
        });
      }
    });

    if (oversizedFiles.length > 0) {
      addMessage('assistant', `⚠️ ${oversizedFiles.join(', ')} ${oversizedFiles.length > 1 ? 'are' : 'is'} too large (max 30MB). Please use smaller files or compress them.`);
    }

    if (validFiles.length > 0) {
      setUploadedFiles(prev => [...prev, ...validFiles]);
    }
  };

  return (
    <div className="flex flex-col h-full max-w-2xl mx-auto w-full">
      {/* Header with back button */}
      {onCancel && (
        <div className="px-4 py-4 border-b border-zinc-200 dark:border-zinc-800">
          <Button
            variant="ghost"
            size="sm"
            onClick={onCancel}
            className="flex items-center gap-2 text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-100"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to presentations
          </Button>
        </div>
      )}

      {/* Messages Area */}
      <div className="flex-1 overflow-y-auto px-4 py-8 space-y-6">
        {messages.map((message, index) => (
          <div key={message.id}>
            <div
              className={cn(
                "flex w-full animate-in slide-in-from-bottom-4 duration-500",
                message.role === 'user' ? 'justify-end' : 'justify-start'
              )}
              style={{ animationDelay: `${index * 0.1}s` }}
            >
              <div
                className={cn(
                  "max-w-[85%] rounded-2xl px-5 py-3.5 shadow-md",
                  message.role === 'user'
                    ? 'bg-gradient-to-br from-orange-500 to-orange-600 text-white'
                    : 'bg-gradient-to-br from-white to-zinc-50 dark:from-zinc-800 dark:to-zinc-900 text-zinc-900 dark:text-zinc-100 border border-zinc-200/50 dark:border-zinc-700/50'
                )}
              >
                {/* File attachments - shown INSIDE the message bubble */}
                {message.attachments && message.attachments.length > 0 && (
                  <div className={cn(
                    "flex flex-wrap gap-2 mb-3",
                    message.attachments.length === 1 ? "justify-center" : ""
                  )}>
                    {message.attachments.map((att, attIdx) => {
                      const isImage = att.type.startsWith('image/');
                      const category = getFileCategory({ name: att.name, type: att.type });
                      const FileIcon = isImage ? ImageIcon
                        : category === 'document' ? FileText
                        : category === 'spreadsheet' ? Table
                        : category === 'presentation' ? Presentation
                        : File;

                      return (
                        <div
                          key={att.id || attIdx}
                          className={cn(
                            "rounded-lg overflow-hidden",
                            isImage && att.previewUrl
                              ? "w-full max-w-[200px]"
                              : "flex items-center gap-2 px-3 py-2 bg-white/20 backdrop-blur-sm"
                          )}
                        >
                          {isImage && att.previewUrl ? (
                            <img
                              src={att.previewUrl}
                              alt={att.name}
                              className="w-full h-auto rounded-lg max-h-[150px] object-cover"
                            />
                          ) : (
                            <>
                              <FileIcon className="w-4 h-4 flex-shrink-0 opacity-80" />
                              <span className="text-xs truncate max-w-[120px]">{att.name}</span>
                            </>
                          )}
                        </div>
                      );
                    })}
                  </div>
                )}
                <div className="text-sm whitespace-pre-wrap leading-relaxed font-['Inter',system-ui,sans-serif]">
                  {renderText(message.content)}
                </div>
              </div>
            </div>

            {/* Agent-provided buttons - hide when slide mode selection is showing */}
            {message.role === 'assistant' && message.buttons && message.buttons.length > 0 && !message.showSlideModeSelection && (
              <div className="flex gap-2 mt-3 ml-2 animate-in slide-in-from-bottom-2 flex-wrap">
                {message.buttons.map((button, btnIndex) => (
                  <Button
                    key={btnIndex}
                    variant={btnIndex === 0 ? "default" : "outline"}
                    size="sm"
                    onClick={() => handleButtonClick(button.action)}
                    disabled={isProcessing}
                    className={cn(
                      "flex items-center gap-2",
                      btnIndex === 0 && "bg-orange-500 hover:bg-orange-600"
                    )}
                  >
                    {button.label}
                  </Button>
                ))}
              </div>
            )}

            {/* Chat Blocks: Theme & Outline - show after last assistant message in planning */}
            {message.role === 'assistant' && index === messages.length - 1 && (stage === 'planning' || stage === 'slide_mode_selection') && (themeBlock || outlineBlock) && (
              <div className="mt-4 mb-3 flex flex-col gap-3 animate-in fade-in slide-in-from-bottom-2 duration-300">
                {/* Theme Block */}
                {themeBlock && (
                  <ThemeChatBlock
                    data={{
                      colors: {
                        background: themeBlock.colors.primary_background,
                        text: themeBlock.colors.primary_text,
                        accent: themeBlock.colors.accent_1,
                      },
                      fonts: {
                        heading: themeBlock.typography.headingFont,
                        body: themeBlock.typography.bodyFont,
                      },
                      logo: themeBlock.branding?.logoUrl,
                      brandName: themeBlock.branding?.brandName || themeBlock.vibeContext,
                    }}
                    onColorChange={(key, hex) => {
                      const colorMap = { background: 'primary_background', text: 'primary_text', accent: 'accent_1' };
                      handleThemeColorChange(colorMap[key], hex);
                    }}
                    onFontChange={(type, font) => {
                      setThemeBlock(prev => prev ? {
                        ...prev,
                        typography: {
                          ...prev.typography,
                          [type === 'heading' ? 'headingFont' : 'bodyFont']: font,
                        }
                      } : prev);
                      // Also update outlineFlow
                      if (outlineFlow) {
                        setOutlineFlow(prev => prev ? {
                          ...prev,
                          theme: {
                            ...prev.theme,
                            typography: {
                              ...(prev.theme?.typography || {}),
                              [type === 'heading' ? 'hero_title' : 'body_text']: { family: font }
                            }
                          }
                        } : prev);
                      }
                    }}
                    onLogoChange={(url) => {
                      setThemeBlock(prev => prev ? {
                        ...prev,
                        branding: { ...prev.branding, logoUrl: url || undefined }
                      } : prev);
                      if (outlineFlow) {
                        setOutlineFlow(prev => prev ? {
                          ...prev,
                          theme: {
                            ...prev.theme,
                            logo: url ? { url } : undefined
                          }
                        } : prev);
                      }
                    }}
                    onBrandNameChange={(name) => {
                      setThemeBlock(prev => prev ? {
                        ...prev,
                        branding: { ...prev.branding, brandName: name }
                      } : prev);
                    }}
                    isEditable={!isProcessing}
                    isLoading={isThemeLoading}
                  />
                )}

                {/* Outline Block - Dropdown with editable content */}
                {outlineBlock && (
                  <DropdownOutlineChatBlock
                    data={{
                      title: outlineBlock.title,
                      slides: outlineBlock.slides.map(s => ({
                        id: s.id,
                        title: s.title,
                        subtitle: s.subtitle,
                        keyPoints: s.keyPoints,
                        content: s.content,
                        isContentLoaded: !!(s.content || (s.keyPoints && s.keyPoints.length > 0)),
                      })),
                    }}
                    onSlideEdit={(slideId, updates) => {
                      setOutlineBlock(prev => {
                        if (!prev) return prev;
                        return {
                          ...prev,
                          slides: prev.slides.map(s =>
                            s.id === slideId ? { ...s, ...updates } : s
                          ),
                        };
                      });
                      if (outlineFlow) {
                        const idx = parseInt(slideId.replace('slide-', ''));
                        const updatedSlides = [...(outlineFlow.slides || [])];
                        if (updatedSlides[idx]) {
                          updatedSlides[idx] = {
                            ...updatedSlides[idx],
                            title: updates.title ?? updatedSlides[idx].title,
                            content: updates.content ?? updatedSlides[idx].content,
                            key_points: updates.keyPoints ?? updatedSlides[idx].key_points,
                          };
                          setOutlineFlow({ ...outlineFlow, slides: updatedSlides });
                        }
                      }
                    }}
                    onSlideAdd={() => {
                      const newSlide = { id: `slide-${outlineBlock.slides.length}`, title: 'New Slide', content: '' };
                      setOutlineBlock(prev => prev ? { ...prev, slides: [...prev.slides, newSlide] } : prev);
                      if (outlineFlow) {
                        setOutlineFlow({ ...outlineFlow, slides: [...(outlineFlow.slides || []), { title: 'New Slide', content: '' }] });
                      }
                    }}
                    onSlideDelete={(slideId) => {
                      setOutlineBlock(prev => {
                        if (!prev) return prev;
                        return { ...prev, slides: prev.slides.filter(s => s.id !== slideId) };
                      });
                      if (outlineFlow) {
                        const idx = parseInt(slideId.replace('slide-', ''));
                        const updatedSlides = [...(outlineFlow.slides || [])];
                        updatedSlides.splice(idx, 1);
                        setOutlineFlow({ ...outlineFlow, slides: updatedSlides });
                      }
                    }}
                    onSlideReorder={(fromIndex, toIndex) => {
                      // Reorder outline block slides
                      setOutlineBlock(prev => {
                        if (!prev) return prev;
                        const newSlides = [...prev.slides];
                        const [movedSlide] = newSlides.splice(fromIndex, 1);
                        newSlides.splice(toIndex, 0, movedSlide);
                        // Re-assign IDs to match new order
                        return {
                          ...prev,
                          slides: newSlides.map((s, i) => ({ ...s, id: `slide-${i}` }))
                        };
                      });
                      // Reorder outline flow slides
                      if (outlineFlow && outlineFlow.slides) {
                        const newSlides = [...outlineFlow.slides];
                        const [movedSlide] = newSlides.splice(fromIndex, 1);
                        newSlides.splice(toIndex, 0, movedSlide);
                        setOutlineFlow({ ...outlineFlow, slides: newSlides });
                      }
                    }}
                    onLoadContent={async (slideId) => {
                      // Find the slide
                      const idx = parseInt(slideId.replace('slide-', ''));
                      const slide = outlineBlock.slides[idx];
                      if (!slide) {
                        return { content: '', keyPoints: [] };
                      }

                      // If content already exists, return it
                      if (slide.content || (slide.keyPoints && slide.keyPoints.length > 0)) {
                        return { content: slide.content || '', keyPoints: slide.keyPoints || [] };
                      }

                      // Build file content context from:
                      // 1. File analysis context (summary of analyzed files)
                      // 2. Uploaded media names
                      // 3. Chat history context about files
                      let fileContentParts: string[] = [];

                      // Add file analysis context if available
                      if (fileAnalysisContext) {
                        fileContentParts.push(`File Analysis:\n${fileAnalysisContext}`);
                      }

                      // Add uploaded media info
                      if (outlineFlow?.uploadedMedia?.length > 0) {
                        const mediaInfo = outlineFlow.uploadedMedia.map((m: any) =>
                          `- ${m.name} (${m.type})`
                        ).join('\n');
                        fileContentParts.push(`Uploaded Files:\n${mediaInfo}`);
                      }

                      // Extract file-related context from chat history
                      const fileRelatedMessages = chatHistory
                        .filter(m => m.content.toLowerCase().includes('file') ||
                                    m.content.toLowerCase().includes('upload') ||
                                    m.content.toLowerCase().includes('document'))
                        .slice(-2)
                        .map(m => `${m.role}: ${m.content}`);
                      if (fileRelatedMessages.length > 0) {
                        fileContentParts.push(`User Instructions:\n${fileRelatedMessages.join('\n')}`);
                      }

                      const fileContent = fileContentParts.length > 0
                        ? fileContentParts.join('\n\n')
                        : undefined;

                      // Call the API to generate content
                      try {
                        const result = await generateSlideContent({
                          slide_title: slide.title,
                          slide_index: idx,
                          total_slides: outlineBlock.slides.length,
                          presentation_topic: outlineFlow?.topic || outlineBlock.title,
                          presentation_context: chatHistory.map(m => `${m.role}: ${m.content}`).slice(-3).join('\n'),
                          existing_key_points: slide.keyPoints,
                          file_content: fileContent,
                        });

                        return {
                          content: result.content,
                          keyPoints: result.key_points,
                        };
                      } catch (error) {
                        console.error('Failed to generate slide content:', error);
                        return { content: '', keyPoints: slide.keyPoints || [] };
                      }
                    }}
                    isEditable={!isProcessing}
                  />
                )}
              </div>
            )}

            {/* Slide Mode Selection - 2 Options: NextGen vs Traditional */}
            {message.role === 'assistant' && message.showSlideModeSelection && (
              <div className="mt-4 animate-in fade-in slide-in-from-bottom-2 duration-300">
                <div className="grid grid-cols-2 gap-4 w-full max-w-[560px]">

                  {/* NextGen - Interactive, Animated, Bold (Recommended) */}
                  <button
                    onClick={() => handleButtonClick('interactive')}
                    disabled={isProcessing}
                    className="group relative flex flex-col rounded-2xl overflow-hidden transition-all duration-500 hover:scale-[1.03] hover:shadow-2xl hover:shadow-orange-500/20 disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100 ring-2 ring-orange-500/50 shadow-xl"
                  >
                    {/* Recommended badge */}
                    <div className="absolute top-3 left-1/2 -translate-x-1/2 z-30">
                      <span className="text-[10px] font-bold bg-gradient-to-r from-orange-500 via-pink-500 to-purple-500 text-white px-3 py-1 rounded-full shadow-lg animate-pulse">
                        ✨ Recommended
                      </span>
                    </div>

                    {/* NextGen Preview - Futuristic, animated feel */}
                    <div className="aspect-[16/10] bg-gradient-to-br from-[#0f0f23] via-[#1a1a3e] to-[#0d0d1f] p-4 relative overflow-hidden">
                      {/* Animated background elements */}
                      <div className="absolute inset-0 overflow-hidden">
                        {/* Glowing orbs */}
                        <div className="absolute -top-8 -left-8 w-32 h-32 bg-gradient-to-br from-orange-500/30 to-pink-500/20 rounded-full blur-2xl group-hover:scale-150 group-hover:opacity-80 transition-all duration-700" />
                        <div className="absolute -bottom-10 -right-10 w-40 h-40 bg-gradient-to-br from-purple-500/25 to-blue-500/15 rounded-full blur-2xl group-hover:scale-125 transition-all duration-700 delay-100" />
                        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-20 h-20 bg-gradient-to-r from-cyan-400/20 to-emerald-400/10 rounded-full blur-xl group-hover:scale-150 transition-all duration-500" />
                        {/* Grid pattern */}
                        <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.03)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.03)_1px,transparent_1px)] bg-[size:20px_20px] opacity-60" />
                        {/* Floating particles */}
                        <div className="absolute top-4 right-6 w-1 h-1 bg-orange-400 rounded-full animate-ping" />
                        <div className="absolute top-8 left-8 w-0.5 h-0.5 bg-purple-400 rounded-full animate-pulse" />
                        <div className="absolute bottom-6 left-12 w-1 h-1 bg-cyan-400 rounded-full animate-ping delay-300" />
                        <div className="absolute bottom-10 right-10 w-0.5 h-0.5 bg-pink-400 rounded-full animate-pulse delay-150" />
                      </div>

                      {/* Content mockup - Bold, interactive elements */}
                      <div className="relative z-10 h-full flex flex-col justify-between pt-5">
                        {/* Title with gradient */}
                        <div className="flex items-center gap-2">
                          <div className="w-3/5 h-3 bg-gradient-to-r from-white via-white/90 to-white/70 rounded-full" />
                          <div className="w-4 h-4 rounded-lg bg-gradient-to-br from-orange-400 to-pink-500 group-hover:rotate-12 transition-transform" />
                        </div>

                        {/* Interactive cards that animate */}
                        <div className="flex gap-2 justify-center items-end">
                          <div className="w-12 h-16 bg-gradient-to-br from-orange-500/80 to-orange-600/60 rounded-xl backdrop-blur-sm border border-orange-400/30 group-hover:translate-y-[-4px] group-hover:shadow-lg group-hover:shadow-orange-500/30 transition-all duration-300 flex flex-col items-center justify-center">
                            <div className="text-[10px] font-black text-white">87%</div>
                            <div className="w-6 h-0.5 bg-white/50 rounded-full mt-1" />
                          </div>
                          <div className="w-14 h-20 bg-gradient-to-br from-purple-500/80 to-pink-500/60 rounded-xl backdrop-blur-sm border border-purple-400/30 group-hover:translate-y-[-6px] group-hover:shadow-lg group-hover:shadow-purple-500/30 transition-all duration-300 delay-75 flex flex-col items-center justify-center">
                            <div className="text-xs font-black text-white">2.4M</div>
                            <div className="w-8 h-0.5 bg-white/50 rounded-full mt-1" />
                          </div>
                          <div className="w-12 h-14 bg-gradient-to-br from-cyan-500/80 to-blue-500/60 rounded-xl backdrop-blur-sm border border-cyan-400/30 group-hover:translate-y-[-3px] group-hover:shadow-lg group-hover:shadow-cyan-500/30 transition-all duration-300 delay-150 flex flex-col items-center justify-center">
                            <div className="text-[10px] font-black text-white">+42</div>
                            <div className="w-5 h-0.5 bg-white/50 rounded-full mt-1" />
                          </div>
                        </div>

                        {/* Bottom accent */}
                        <div className="flex gap-2 items-center">
                          <div className="flex-1 h-1 bg-gradient-to-r from-orange-500/60 via-purple-500/40 to-transparent rounded-full" />
                          <div className="w-6 h-6 rounded-full bg-gradient-to-br from-white/20 to-white/5 backdrop-blur-sm flex items-center justify-center">
                            <div className="w-2 h-2 bg-white/60 rounded-full" />
                          </div>
                        </div>
                      </div>
                    </div>

                    {/* Label */}
                    <div className="bg-gradient-to-r from-orange-500 via-orange-500 to-pink-500 px-4 py-3 text-white">
                      <div className="font-bold text-base tracking-tight">NextGen</div>
                      <div className="text-[11px] text-white/80 leading-tight mt-0.5">Interactive • Animated • Bold</div>
                    </div>
                  </button>

                  {/* Traditional - Clean, Professional, PPT-ready */}
                  <button
                    onClick={() => handleButtonClick('static')}
                    disabled={isProcessing}
                    className="group relative flex flex-col rounded-2xl overflow-hidden transition-all duration-300 hover:scale-[1.02] hover:shadow-xl disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100 border border-zinc-200 dark:border-zinc-700 bg-white dark:bg-zinc-900"
                  >
                    {/* Traditional Preview - Clean, professional PPT style */}
                    <div className="aspect-[16/10] bg-gradient-to-br from-slate-50 to-zinc-100 dark:from-zinc-800 dark:to-zinc-900 p-4 relative overflow-hidden">
                      {/* Subtle professional background */}
                      <div className="absolute top-0 right-0 w-24 h-24 bg-blue-500/5 rounded-full blur-2xl" />
                      <div className="absolute bottom-0 left-0 w-20 h-20 bg-slate-400/5 rounded-full blur-xl" />

                      {/* Content mockup - Professional presentation style */}
                      <div className="relative z-10 h-full flex flex-col justify-between">
                        {/* Title bar */}
                        <div className="space-y-1">
                          <div className="w-4/5 h-2.5 bg-zinc-800 dark:bg-zinc-200 rounded-sm" />
                          <div className="w-1/2 h-1.5 bg-zinc-400 dark:bg-zinc-500 rounded-sm" />
                        </div>

                        {/* Two-column layout with chart and text */}
                        <div className="flex gap-3 flex-1 mt-3">
                          {/* Left: Mini chart */}
                          <div className="w-1/2 bg-white dark:bg-zinc-800 rounded-lg p-2 shadow-sm border border-zinc-100 dark:border-zinc-700">
                            <div className="flex items-end justify-around h-full gap-1 pb-1">
                              <div className="w-3 bg-blue-500 rounded-t-sm" style={{height: '60%'}} />
                              <div className="w-3 bg-blue-400 rounded-t-sm" style={{height: '80%'}} />
                              <div className="w-3 bg-blue-500 rounded-t-sm" style={{height: '45%'}} />
                              <div className="w-3 bg-blue-400 rounded-t-sm" style={{height: '90%'}} />
                            </div>
                          </div>

                          {/* Right: Bullet points */}
                          <div className="w-1/2 flex flex-col justify-center gap-1.5">
                            <div className="flex items-center gap-1.5">
                              <div className="w-1.5 h-1.5 bg-blue-500 rounded-full flex-shrink-0" />
                              <div className="w-full h-1.5 bg-zinc-300 dark:bg-zinc-600 rounded-sm" />
                            </div>
                            <div className="flex items-center gap-1.5">
                              <div className="w-1.5 h-1.5 bg-blue-500 rounded-full flex-shrink-0" />
                              <div className="w-4/5 h-1.5 bg-zinc-300 dark:bg-zinc-600 rounded-sm" />
                            </div>
                            <div className="flex items-center gap-1.5">
                              <div className="w-1.5 h-1.5 bg-blue-500 rounded-full flex-shrink-0" />
                              <div className="w-3/5 h-1.5 bg-zinc-300 dark:bg-zinc-600 rounded-sm" />
                            </div>
                          </div>
                        </div>

                        {/* Footer */}
                        <div className="flex justify-between items-center mt-2">
                          <div className="w-12 h-3 bg-zinc-200 dark:bg-zinc-700 rounded-sm" />
                          <div className="text-[8px] text-zinc-400 dark:text-zinc-500 font-medium">3 / 12</div>
                        </div>
                      </div>
                    </div>

                    {/* Label */}
                    <div className="bg-zinc-100 dark:bg-zinc-800 px-4 py-3 text-zinc-800 dark:text-zinc-200 border-t border-zinc-200 dark:border-zinc-700">
                      <div className="font-bold text-base">Traditional</div>
                      <div className="text-[11px] text-zinc-500 dark:text-zinc-400 leading-tight mt-0.5">Clean • Professional • PPTX-ready</div>
                    </div>
                  </button>

                </div>

                {/* Continue chatting link - small below */}
                <div className="mt-4 text-center">
                  <button
                    onClick={() => {
                      setStage('chat');
                      // Remove the slide mode selection from the last message
                      setMessages(prev => prev.map((m, i) =>
                        i === prev.length - 1 ? { ...m, showSlideModeSelection: false } : m
                      ));
                    }}
                    className="text-xs text-zinc-400 hover:text-zinc-600 dark:hover:text-zinc-300 transition-colors"
                  >
                    or continue chatting to refine
                  </button>
                </div>
              </div>
            )}

          </div>
        ))}

        {/* Agent Typing/Status Indicator - Inline with chat as assistant message */}
        {isAgentTyping && (
          <div className="flex w-full animate-in slide-in-from-bottom-4 duration-300 justify-start">
            <div className="max-w-[85%] rounded-2xl px-5 py-3.5 shadow-md bg-gradient-to-br from-white to-zinc-50 dark:from-zinc-800 dark:to-zinc-900 text-zinc-900 dark:text-zinc-100 border border-zinc-200/50 dark:border-zinc-700/50">
              {thinkingSteps.length > 0 ? (
                <ThinkingStatusDisplay
                  steps={thinkingSteps}
                  isActive={true}
                />
              ) : streamingText ? (
                /* Show streaming text line-by-line like slide gen chat panel */
                <div className="space-y-1">
                  {streamingText
                    .split('\n')
                    .filter(line => line.trim())
                    .slice(-6) // Show last 6 lines to avoid overwhelming
                    .map((line, idx, arr) => {
                      // Skip lines that look like JSON
                      if (line.trim().startsWith('{') || line.trim().startsWith('"') || line.trim().startsWith('[')) {
                        return null;
                      }
                      // Clean up markdown and formatting
                      const cleanLine = line
                        .replace(/\*\*/g, '')
                        .replace(/```json/g, '')
                        .replace(/```/g, '')
                        .trim();
                      if (!cleanLine) return null;

                      const isLatest = idx === arr.length - 1;
                      return (
                        <div
                          key={idx}
                          className={cn(
                            "flex items-start gap-2 text-sm animate-in fade-in duration-200",
                            isLatest ? "text-orange-600 dark:text-orange-400" : "text-zinc-500 dark:text-zinc-500"
                          )}
                        >
                          <span className="mt-0.5 flex-shrink-0 text-xs">
                            {isLatest ? '›' : '•'}
                          </span>
                          <span className={cn(
                            "leading-relaxed",
                            isLatest && "font-medium"
                          )}>
                            {cleanLine.length > 100 ? cleanLine.slice(0, 100) + '...' : cleanLine}
                          </span>
                        </div>
                      );
                    })
                    .filter(Boolean)
                  }
                  {/* Typing indicator */}
                  <div className="text-xs text-zinc-400 pl-5">
                    thinking...
                  </div>
                </div>
              ) : (
                <div className="text-sm text-zinc-600 dark:text-zinc-400">
                  {statusPhase === 'analyzing' ? 'Analyzing your files...' :
                   statusPhase === 'researching' ? `Researching: ${statusMessage || 'gathering info'}` :
                   statusPhase === 'scraping' ? 'Reading content...' :
                   statusMessage || 'Thinking...'}
                </div>
              )}
            </div>
          </div>
        )}

        {/* File Upload Confirmation Dialog */}
        {pendingFileConfirmation && (
          <div className="flex w-full animate-in slide-in-from-bottom-4 duration-300 justify-start">
            <div className="max-w-[85%] rounded-xl border bg-white dark:bg-zinc-900 shadow-lg border-orange-200 dark:border-orange-700/50 overflow-hidden">
              <div className="px-4 py-3 bg-orange-50 dark:bg-orange-900/20 border-b border-orange-100 dark:border-orange-800/30">
                <p className="text-sm font-medium text-zinc-800 dark:text-zinc-200">
                  How should I use {pendingFileConfirmation.files.length === 1 ? 'this file' : 'these files'}?
                </p>
                <div className="flex gap-1 mt-1.5 flex-wrap">
                  {pendingFileConfirmation.files.map((f, i) => (
                    <span key={i} className="text-[10px] px-1.5 py-0.5 rounded bg-orange-100 dark:bg-orange-800/30 text-orange-700 dark:text-orange-300">
                      {f.file.name}
                    </span>
                  ))}
                </div>
              </div>
              <div className="p-3 flex gap-2">
                <button
                  onClick={() => handleFileConfirmation(true)}
                  className="flex-1 px-3 py-2 rounded-lg bg-orange-500 hover:bg-orange-600 text-white text-sm font-medium transition-colors"
                >
                  Use Content Directly
                  <span className="block text-[10px] opacity-80 font-normal">Include exact content in slides</span>
                </button>
                <button
                  onClick={() => handleFileConfirmation(false)}
                  className="flex-1 px-3 py-2 rounded-lg bg-zinc-100 dark:bg-zinc-800 hover:bg-zinc-200 dark:hover:bg-zinc-700 text-zinc-700 dark:text-zinc-300 text-sm font-medium transition-colors"
                >
                  Reference Only
                  <span className="block text-[10px] opacity-70 font-normal">For style/design inspiration</span>
                </button>
              </div>
            </div>
          </div>
        )}


        {/* Fallback: Show "Continue" button after 1+ user messages if no outline generated yet */}
        {!isAgentTyping && !isProcessing && (stage === 'conversing' || stage === 'chat') && messages.filter(m => m.role === 'user').length >= 1 && (
          <div className="flex justify-center mt-4 animate-in fade-in">
            <button
              onClick={() => {
                // Check if user requested detailed mode in their messages
                const userRequestedDetailed = chatHistory.some(msg =>
                  msg.role === 'user' &&
                  (msg.content.toLowerCase().includes('detailed') ||
                   msg.content.toLowerCase().includes('in-depth') ||
                   msg.content.toLowerCase().includes('comprehensive'))
                );
                const detailLevel = userRequestedDetailed ? 'detailed' : 'quick';

                // Store detail level and show slide mode selection
                setCollectedData(prev => ({ ...prev, presentationType: 'simple', detailLevel }));
                setStage('slide_mode_selection');

                // Add message with slide mode selection buttons
                addMessage(
                  'assistant',
                  "Choose your presentation style:",
                  undefined,
                  undefined,
                  undefined,
                  true // showSlideModeSelection
                );
              }}
              className="text-orange-500 hover:text-orange-600 text-sm font-medium transition-colors flex items-center gap-1"
            >
              Continue
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
              </svg>
            </button>
          </div>
        )}

        <div ref={messagesEndRef} />
      </div>

      {/* Input Area - Sticky Bottom */}
      {stage !== 'slide_mode_selection' && stage !== 'confirmed' && (
        <div className="sticky bottom-0 z-10 bg-white/80 dark:bg-black/80 backdrop-blur-md border-t border-zinc-200 dark:border-zinc-800">
          <div className="px-6 py-4">
            {/* Pending files preview - shown before sending */}
            {uploadedFiles.length > 0 && (
              <div className="mb-3 flex flex-wrap gap-2 animate-in fade-in slide-in-from-bottom-2">
                {uploadedFiles.map((fileData, index) => {
                  const isImage = fileData.file.type.startsWith('image/');
                  const category = getFileCategory({ name: fileData.file.name, type: fileData.file.type });
                  const FileIcon = isImage ? ImageIcon
                    : category === 'document' ? FileText
                    : category === 'spreadsheet' ? Table
                    : category === 'presentation' ? Presentation
                    : File;

                  return (
                    <div
                      key={index}
                      className="group relative flex items-center gap-2 bg-gradient-to-br from-zinc-100 to-zinc-50 dark:from-zinc-800 dark:to-zinc-900 rounded-xl px-3 py-2 text-sm border border-zinc-200 dark:border-zinc-700 shadow-sm hover:shadow-md transition-shadow"
                    >
                      {/* Image thumbnail or icon */}
                      {isImage && fileData.previewUrl ? (
                        <img
                          src={fileData.previewUrl}
                          alt={fileData.file.name}
                          className="w-10 h-10 rounded-lg object-cover"
                        />
                      ) : (
                        <div className={cn(
                          "w-10 h-10 rounded-lg flex items-center justify-center",
                          category === 'document' ? "bg-blue-100 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400"
                          : category === 'spreadsheet' ? "bg-green-100 dark:bg-green-900/30 text-green-600 dark:text-green-400"
                          : category === 'presentation' ? "bg-orange-100 dark:bg-orange-900/30 text-orange-600 dark:text-orange-400"
                          : "bg-zinc-200 dark:bg-zinc-700 text-zinc-600 dark:text-zinc-400"
                        )}>
                          <FileIcon className="w-5 h-5" />
                        </div>
                      )}
                      <div className="flex flex-col min-w-0">
                        <span className="text-zinc-800 dark:text-zinc-200 truncate max-w-[140px] text-sm font-medium">
                          {fileData.file.name}
                        </span>
                        <span className="text-zinc-500 dark:text-zinc-500 text-xs">
                          {formatFileSize(fileData.file.size)}
                        </span>
                      </div>
                      <button
                        onClick={() => handleRemoveFile(index)}
                        className="absolute -top-2 -right-2 p-1 bg-zinc-700 dark:bg-zinc-600 text-white rounded-full opacity-0 group-hover:opacity-100 transition-opacity hover:bg-red-500"
                      >
                        <X className="w-3 h-3" />
                      </button>
                    </div>
                  );
                })}
              </div>
            )}

            <div
              className={cn(
                "flex gap-3 items-end bg-white dark:bg-zinc-800 rounded-2xl border border-zinc-200 dark:border-zinc-700 shadow-sm hover:border-zinc-300 dark:hover:border-zinc-600 transition-colors",
                isDraggingOver && "border-orange-400 dark:border-orange-500 bg-orange-50 dark:bg-orange-950/20"
              )}
              onDragOver={handleDragOver}
              onDragLeave={handleDragLeave}
              onDrop={handleDrop}
            >
              <div className="flex-1 relative">
                <textarea
                  ref={inputRef}
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onKeyDown={handleKeyPress}
                  placeholder={isDraggingOver ? "Drop files here..." : (isAgentTyping ? "Type your next message..." : "Type your message or drag & drop files...")}
                  disabled={isProcessing}
                  className="w-full bg-transparent border-0 text-[#383636] dark:text-gray-200 placeholder:text-zinc-400 dark:placeholder:text-zinc-500 focus:outline-none focus-visible:outline-none focus:ring-0 focus-visible:ring-0 pt-4 pb-4 pl-4 pr-2 resize-none text-base overflow-y-auto max-h-[400px] min-h-[60px] font-sans"
                  rows={1}
                />
              </div>
              <div className="flex items-center gap-2 pb-2 pr-2">
                <input
                  ref={fileInputRef}
                  type="file"
                  multiple
                  className="hidden"
                  onChange={handleFileUpload}
                  accept=".pdf,.doc,.docx,.txt,.md,.jpg,.jpeg,.png,.gif,.webp,.svg,.csv,.xls,.xlsx,.ppt,.pptx"
                />
                <Button
                  onClick={() => fileInputRef.current?.click()}
                  disabled={isProcessing}
                  size="icon"
                  variant="ghost"
                  className={cn(
                    "h-8 w-8 rounded-lg relative transition-colors",
                    uploadedFiles.length > 0
                      ? "text-orange-600 dark:text-orange-400 hover:text-orange-700 hover:bg-orange-50 dark:hover:bg-orange-900/20"
                      : "text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-100 hover:bg-zinc-100 dark:hover:bg-zinc-700"
                  )}
                >
                  <Paperclip className="w-4 h-4" />
                  {uploadedFiles.length > 0 && (
                    <span className="absolute -top-1 -right-1 w-4 h-4 bg-orange-500 text-white text-[10px] font-bold rounded-full flex items-center justify-center">
                      {uploadedFiles.length}
                    </span>
                  )}
                </Button>
                <Button
                  onClick={() => {
                    // TODO: Implement link input functionality
                    console.log('Link button clicked');
                  }}
                  disabled={isProcessing}
                  size="icon"
                  variant="ghost"
                  className="h-8 w-8 rounded-lg text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-100 hover:bg-zinc-100 dark:hover:bg-zinc-700"
                >
                  <LinkIcon className="w-4 h-4" />
                </Button>
                <VoiceRecorder
                  onTranscript={(text) => {
                    setInput(prev => {
                      const newText = prev.trim() ? `${prev} ${text}` : text;
                      return newText;
                    });
                    setTimeout(() => inputRef.current?.focus(), 100);
                  }}
                  onError={(error) => {
                    console.error('Voice recording error:', error);
                  }}
                  disabled={isProcessing || isAgentTyping}
                  size="sm"
                  variant="minimal"
                  className="h-8 w-8 rounded-lg"
                />
                <Button
                  onClick={() => handleSendMessage()}
                  disabled={(!input.trim() && uploadedFiles.length === 0) || isAgentTyping || isProcessing}
                  size="icon"
                  className="h-10 w-10 rounded-xl bg-orange-500 hover:bg-orange-600 shrink-0 disabled:opacity-50"
                >
                  {isProcessing ? (
                    <Sparkles className="w-4 h-4 animate-pulse" />
                  ) : (
                    <Send className="w-4 h-4" />
                  )}
                </Button>
              </div>
            </div>

            <p className="text-xs text-zinc-500 dark:text-zinc-400 mt-2 text-center">
              Press Enter to send, Shift+Enter for new line
            </p>
          </div>
        </div>
      )}

      {/* Credit Warning Dialog */}
      {creditWarningData && (
        <CreditWarningDialog
          open={showCreditWarning}
          onClose={() => {
            setShowCreditWarning(false);
            setCreditWarningData(null);
          }}
          remainingCredits={creditWarningData.remaining}
          requiredCredits={creditWarningData.required}
          slideCount={creditWarningData.slideCount}
          planName={creditWarningData.planName}
          mode={creditWarningData.mode}
          onProceed={() => {
            // User confirmed to proceed (either with overage or partial generation)
            if (creditWarningData.pendingSlideMode) {
              proceedWithGeneration(creditWarningData.pendingSlideMode);
            }
            setShowCreditWarning(false);
            setCreditWarningData(null);
          }}
        />
      )}
    </div>
  );
};

export default ConversationalOnboarding;
